### ISSUE TITLE
problem with data loading in Spacenet

### ISSUE THREAD

**Issue by Dinh-Hung-Tu** [nilearn/nilearn#1060]
plot_haxby_space_net.py spits the following  error:

Traceback (most recent call last):

  File "<ipython-input-63-b5991c7a5138>", line 1, in <module>
    decoder.fit(X_train, y_train)

  File "C:\Users\~\AppData\Roaming\Python\Python27\site-packages\nilearn\decoding\space_net.py", line 775, in fit
    X = self.masker_.fit_transform(X)

  File "C:\Users\~AppData\Roaming\Python\Python27\site-packages\nilearn\input_data\base_masker.py", line 203, in fit_transform
    return self.fit(X, **fit_params

  File "C:\Users\~\AppData\Roaming\Python\Python27\site-packages\nilearn\input_data\nifti_masker.py", line 231, in fit
    imgs, verbose=max(0, self.verbose - 1), **mask_args)

  File "C:\Users\~\Anaconda\lib\site-packages\sklearn\externals\joblib\memory.py", line 483, in __call__
    return self._cached_call(args, kwargs)[0]

  File "C:\Users\~\Anaconda\lib\site-packages\sklearn\externals\joblib\memory.py", line 430, in _cached_call
    out, metadata = self.call(*args, **kwargs)

  File "C:\Users\~\Anaconda\lib\site-packages\sklearn\externals\joblib\memory.py", line 675, in call
    output = self.func(*args, **kwargs)

  File "C:\Users\~\AppData\Roaming\Python\Python27\site-packages\nilearn\masking.py", line 287, in compute_epi_mask
    return new_img_like(epi_img, mask, affine)

  File "C:\Users\~\AppData\Roaming\Python\Python27\site-packages\nilearn\image\image.py", line 574, in new_img_like
    if (not isinstance(ref_niimg, _basestring)

TypeError: isinstance() arg 2 must be a class, type, or tuple of classes and types

**Comment by AlexandreAbraham** [comment]
Can you tell us which version of python you are using? Type:
`python --version`

**Comment by Dinh-Hung-Tu** [comment]
Thank you. I used to use Python 3 on Spyder. I am afraid that the problem is caused by conflicting presence of Python 3 and Python 2. This issue disappeared as I uninstall everything and currently it works with Anaconda Python 3.5.1 :: Anaconda 2.5.0 (64-bit).

**Comment by lesteve** [comment]
@Dinh-Hung-Tu For the record you can use markdown in comments for example this is useful to use triple back-quotes for formatting error messages or code snippets. Look at https://help.github.com/articles/creating-and-highlighting-code-blocks/ for more details.

**Comment by Dinh-Hung-Tu** [comment]
@lesteve  I noted and formatted accordingly. Thanks for your recommendation.

**Comment by lesteve** [comment]
> @lesteve I noted and formatted accordingly. Thanks for your recommendation. 

Cheers, it does help for readability.
