### ISSUE TITLE
building docs bsddb error 'file size not a multiple of the pagesize'

### ISSUE THREAD

**Issue by salma1601** [nilearn/nilearn#1270]
I am not sure this is the right place to ask the question, but I started having a strange error when I use `make html` to build my nilearn doc after it was working alright

>Exception occurred:
  File "/home/salma/anaconda2/lib/python2.7/bsddb/__init__.py", line 364, in hashopen
    d.open(file, db.DB_HASH, flags, mode)
DBInvalidArgError: (22, 'Invalid argument -- BDB3037 ./auto_examples/searchindex: file size not a multiple of the pagesize')

**Comment by GaelVaroquaux** [comment]
You can try removing doc/_build/doctrees.

If that doesn't work, please post the full traceback here.

**Comment by salma1601** [comment]
It didn't work

\# Sphinx version: 1.4.6
\# Python version: 2.7.12 (CPython)
\# Docutils version: 0.12 release
\# Jinja2 version: 2.8
\# Last messages:
\#   
\#   copying static files...
\#   done
\#   copying extra files...
\#   done
\#   dumping search index in English (code: en) ...
\#   done
\#   dumping object inventory...
\#   done
\#   build succeeded, 82 warnings.
\# Loaded extensions:
\#   numpydoc.numpydoc (unknown version) from /home/salma/CODE/Parietal/nilearn/doc/sphinxext/numpydoc/numpydoc.pyc
\#   sphinx.ext.autodoc (1.4.6) from /home/salma/anaconda2/lib/python2.7/site-packages/sphinx/ext/autodoc.pyc
\#   sphinx.ext.intersphinx (1.4.6) from /home/salma/anaconda2/lib/python2.7/site-packages/sphinx/ext/intersphinx.pyc
\#   sphinx_gallery.gen_gallery (unknown version) from /home/salma/CODE/Parietal/nilearn/doc/sphinxext/sphinx_gallery/gen_gallery.pyc
\#   alabaster (0.7.9) from /home/salma/anaconda2/lib/python2.7/site-packages/alabaster/__init__.pyc
\#   sphinx.ext.autosummary (1.4.6) from /home/salma/anaconda2/lib/python2.7/site-packages/sphinx/ext/autosummary/__init__.pyc
\#   sphinx.ext.imgmath (1.4.6) from /home/salma/anaconda2/lib/python2.7/site-packages/sphinx/ext/imgmath.pyc
Traceback (most recent call last):
  File "/home/salma/anaconda2/lib/python2.7/site-packages/sphinx/cmdline.py", line 244, in main
    app.build(opts.force_all, filenames)
  File "/home/salma/anaconda2/lib/python2.7/site-packages/sphinx/application.py", line 315, in build
    self.emit('build-finished', None)
  File "/home/salma/anaconda2/lib/python2.7/site-packages/sphinx/application.py", line 551, in emit
    results.append(callback(self, *args))
  File "/home/salma/CODE/Parietal/nilearn/doc/sphinxext/sphinx_gallery/docs_resolv.py", line 436, in embed_code_links
    _embed_code_links(app, gallery_conf, gallery_dir)
  File "/home/salma/CODE/Parietal/nilearn/doc/sphinxext/sphinx_gallery/docs_resolv.py", line 331, in _embed_code_links
    gallery_dir)
  File "/home/salma/CODE/Parietal/nilearn/doc/sphinxext/sphinx_gallery/docs_resolv.py", line 214, in __init__
    sindex = get_data(searchindex_url, gallery_dir)
  File "/home/salma/CODE/Parietal/nilearn/doc/sphinxext/sphinx_gallery/docs_resolv.py", line 62, in get_data
    search_index = shelve.open(cached_file)
  File "/home/salma/anaconda2/lib/python2.7/shelve.py", line 243, in open
    return DbfilenameShelf(filename, flag, protocol, writeback)
  File "/home/salma/anaconda2/lib/python2.7/shelve.py", line 227, in __init__
    Shelf.__init__(self, anydbm.open(filename, flag), protocol, writeback)
  File "/home/salma/anaconda2/lib/python2.7/anydbm.py", line 85, in open
    return mod.open(file, flag, mode)
  File "/home/salma/anaconda2/lib/python2.7/dbhash.py", line 18, in open
    return bsddb.hashopen(file, flag, mode)
  File "/home/salma/anaconda2/lib/python2.7/bsddb/__init__.py", line 364, in hashopen
    d.open(file, db.DB_HASH, flags, mode)
DBInvalidArgError: (22, 'Invalid argument -- BDB3037 ./auto_examples/searchindex: file size not a multiple of the pagesize')

**Comment by GaelVaroquaux** [comment]
OK, try removing doc/auto_examples/searchindex

@titan-C: that's probably the sphinx-gallery cache that gets corrupted.
We should capture that error, and reissue it was a suggestion to remove
that file, if that solves the problem.

**Comment by salma1601** [comment]
now it works, thanks !

**Comment by GaelVaroquaux** [comment]
Closing this issue. @Titan-C : can you please capture this error in sphinx-gallery and reraise it with a more meaningful message.
