### ISSUE TITLE
CircleCI build crashes with matplotlib 1.5

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#1413]
Users who have 1.5 version have troubles building their documentation. 

```python
../examples/02_decoding/plot_haxby_anova_svm.py failed to execute correctly:Traceback (most recent call last):
  File "/home/kamalakar/Kamalakar/work/nilearn/doc/sphinxext/sphinx_gallery/gen_rst.py", line 450, in execute_code_block
    exec(code_block, example_globals)
  File "<string>", line 16, in <module>
  File "/home/kamalakar/Kamalakar/work/nilearn/nilearn/plotting/img_plotting.py", line 986, in plot_stat_map
    **kwargs)
  File "/home/kamalakar/Kamalakar/work/nilearn/nilearn/plotting/img_plotting.py", line 172, in _plot_img_with_bg
    colorbar=colorbar)
  File "/home/kamalakar/Kamalakar/work/nilearn/nilearn/plotting/displays.py", line 512, in init_with_figure
    return cls(cut_coords, axes, black_bg, **kwargs)
  File "/home/kamalakar/Kamalakar/work/nilearn/nilearn/plotting/displays.py", line 459, in __init__
    self._init_axes(**kwargs)
  File "/home/kamalakar/Kamalakar/work/nilearn/nilearn/plotting/displays.py", line 936, in _init_axes
    ax.set_facecolor(facecolor)
AttributeError: 'Axes' object has no attribute 'set_facecolor'
```
```set_facecolor``` seems to be implemented from matplotlib 2.0 but not from 1.5 if I understood correctly.

Can anybody see this problem ? It would be great if you could try at some time. Thanks.

**Comment by GaelVaroquaux** [comment]
Are you sure that this happens on master?

I merged a PR from @arthurmensch a week ago that fixes this:
https://github.com/nilearn/nilearn/pull/1395

**Comment by KamalakerDadi** [comment]
>Are you sure that this happens on master?

Yes, it happened to me on master. When I hacked a bit code to check for >= 2.0, it succeeded.

How do I see on which version of matplotlib is CircleCI build running ?

**Comment by GaelVaroquaux** [comment]
Good point! I just pushed a fix to master.

**Comment by KamalakerDadi** [comment]
>Good point! I just pushed a fix to master.

Missed at Line935 https://github.com/nilearn/nilearn/blob/master/nilearn/plotting/displays.py#L935

**Comment by GaelVaroquaux** [comment]
Indeed. I pushed a new fix :)
