### ISSUE TITLE
Test suite fails

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#1527]
I am trying to run the test suite for the newest release (`0.3.1`) for the Gentoo package, but I am getting at least [one error and one fail](https://bpaste.net/show/72848b09f50b).

Could you help me fgure out what went wrong here? The error seems to be related to joblib, which may be intractable, because we use the system joblib (`0.11`) and not the one which nilearn bundles - but what about the fail?

**Comment by GaelVaroquaux** [comment]
Can you give paste the error messages, elsewhere we cannot help.

**Comment by TheChymera** [comment]
Please look at the full test suite output linked above to get a more complete picture of what is happening. Here is what I suspect to be the issue:

```
======================================================================
ERROR: nilearn.input_data.tests.test_nifti_masker.test_joblib_cache
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/sci-biology/nilearn-0.3.1/work/nilearn-0.3.1/nilearn/input_data/tests/test_nifti_masker.py", line 241, in test_joblib_cache
    X = masker.transform(mask_img)
  File "/var/tmp/portage/sci-biology/nilearn-0.3.1/work/nilearn-0.3.1/nilearn/input_data/base_masker.py", line 176, in transform
    return self.transform_single_imgs(imgs, confounds)
  File "/var/tmp/portage/sci-biology/nilearn-0.3.1/work/nilearn-0.3.1/nilearn/input_data/nifti_masker.py", line 287, in transform_single_imgs
    shelve=self._shelving)(
  File "/var/tmp/portage/sci-biology/nilearn-0.3.1/work/nilearn-0.3.1/nilearn/_utils/cache_mixin.py", line 298, in _cache
    **kwargs)
  File "/var/tmp/portage/sci-biology/nilearn-0.3.1/work/nilearn-0.3.1/nilearn/_utils/cache_mixin.py", line 220, in cache
    "%s %s was given." % (memory, type(memory)))
TypeError: 'memory' argument must be a string or a joblib.Memory object. Memory(cachedir='/var/tmp/portage/sci-biology/nilearn-0.3.1/temp/tmp7d7UDf/joblib') <class 'sklearn.externals.joblib.memory.Memory'> was given.

======================================================================
FAIL: nilearn.datasets.tests.test_atlas.test_fail_fetch_atlas_harvard_oxford
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/var/tmp/portage/sci-biology/nilearn-0.3.1/work/nilearn-0.3.1/nilearn/datasets/tests/test_atlas.py", line 204, in test_fail_fetch_atlas_harvard_oxford
    assert_equal(len(ho.labels), 5)
AssertionError: 97 != 5
    '97 != 5' = '%s != %s' % (safe_repr(97), safe_repr(5))
    '97 != 5' = self._formatMessage('97 != 5', '97 != 5')
>>  raise self.failureException('97 != 5')
```

**Comment by GaelVaroquaux** [comment]
The first error is clearly because you're unbundling joblib. But by doing
this, you've broken cache support under nilearn. In effect you've broken
nilearn.


The second error makes no sense to me. It seems that the code is not
operating on the test dummy file, written in the temp directory, but on
the actual Harvard Oxford file. Maybe the actual Harvard Oxford file is
downloaded from the web, but the question is why?

**Comment by TheChymera** [comment]
you mean it could be that it conflicts with an already present file? how can I check?

**Comment by NicolasGensollen** [comment]
I am closing this since it is outdated and doesn't seem to be related to a bug in nilearn. 
Feel free to re-open an issue if needed.
