### ISSUE TITLE
error in nifti masker with nifti-2. 

### ISSUE THREAD

**Issue by jennyrgilb** [nilearn/nilearn#1611]
I am getting an error that the glmax is missing when I use nifti.masker.fit.transform on nifti2 formatted data. 

**Error**
Traceback (most recent call last):
  File "img_nested_app_v_unapp.py", line 85, in <module>
    fmri_trans = nifti_masker.fit_transform(fmri_subjs)
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib/python2.7/site-packages/nilearn/input_data/base_masker.py", line 206, in fit_transform
    return self.fit(**fit_params).transform(X, confounds=confounds)
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib/python2.7/site-packages/nilearn/input_data/base_masker.py", line 176, in transform
    return self.transform_single_imgs(imgs, confounds)
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib/python2.7/site-packages/nilearn/input_data/nifti_masker.py", line 292, in transform_single_imgs
    copy=copy
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib64/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 562, in __call__
    return self._cached_call(args, kwargs)[0]
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib64/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 510, in _cached_call
    out, metadata = self.call(*args, **kwargs)
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib64/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 744, in call
    output = self.func(*args, **kwargs)
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib/python2.7/site-packages/nilearn/input_data/nifti_masker.py", line 52, in filter_and_mask
    confounds=confounds, copy=copy)
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib/python2.7/site-packages/nilearn/input_data/base_masker.py", line 92, in filter_and_extract
    imgs, parameters['smoothing_fwhm'])
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib64/python2.7/site-packages/sklearn/externals/joblib/memory.py", line 362, in __call__
    return self.func(*args, **kwargs)
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib/python2.7/site-packages/nilearn/image/image.py", line 271, in smooth_img
    ret.append(new_img_like(img, filtered, affine, copy_header=True))
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib/python2.7/site-packages/nilearn/image/image.py", line 638, in new_img_like
    header['glmax'] = 0.
  File "/usr/share/Modules/software/CentOS-7/python_modules/2.7/lib/python2.7/site-packages/nibabel/wrapstruct.py", line 326, in __setitem__
    self._structarr[item] = value
ValueError: no field of name glmax

**Code** 
ni2_funcs = (nib.Nifti2Image.from_image(nib.load(func)) for func in all_func)
ni2_concat = nib.concat_images(ni2_funcs, check_affines=False, axis=3)
outfile=os.path.join(basepath,'concatenated_imagine.nii')
ni2_concat.to_filename(outfile)

fmri_subjs=os.path.join(basepath, 'concatenated_imagine.nii')
average_ana=os.path.join(basepath,'CS_avg_mprage_image.nii.gz')
imag_mask=os.path.join('/projects','niblab','scripts','nilean_stuff','power_roimask_4bi.nii.gz')

stim = os.path.join('/projects','niblab','scripts','nilean_stuff','label_all_sub.csv')
labels = np.recfromcsv(stim, delimiter=",")
print(labels)

y_mask = labels['label']
subs = labels['sub']

condition_mask = np.logical_or(y_mask == b'app',y_mask == b'unapp')
print(condition_mask.shape)
y = y_mask[condition_mask]
print(y)
n_conditions = np.size(np.unique(y))
 
nifti_masker = NiftiMasker(mask_img=imag_mask,
                           smoothing_fwhm=4,standardize=True,
                           memory="nilearn_cache",memory_level=1)

fmri_trans = nifti_masker.fit_transform(fmri_subjs)
print(fmri_trans)
X = fmri_trans[condition_mask]
subs = subs[condition_mask]

**Comment by bthirion** [comment]
This is the issue addressed  in #1610, isnt'it ?

**Comment by KamalakerDadi** [comment]
>This is the issue addressed  in #1610, isnt'it ?

Yes. We are trying to fix it in the mentioned PR #1610

**Comment by jennyrgilb** [comment]
Yep -- looks like someone added this before i did. Thanks for being quick KamalakerDadi!

**Comment by KamalakerDadi** [comment]
Thank you for reporting the issue @jennyrgilb  Closing with #1610 .
