### ISSUE TITLE
Cannot install nilearn with `python setup.py`

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#1640]
```
chymera@zenhost ~/src/nilearn $ git rev-parse HEAD
7f4e4471d5b6995422d051e80e6cf176e8e1c795
chymera@zenhost ~/src/nilearn $ python setup.py develop --install-dir ~/.python_develop/
Traceback (most recent call last):
  File "setup.py", line 52, in <module>
    module_check_fn(is_nilearn_installing=True)
  File "<string>", line 110, in _check_module_dependencies
  File "<string>", line 60, in _import_module_with_version_check
  File "/usr/lib64/python3.5/site-packages/sklearn/__init__.py", line 57, in <module>
    from .base import clone
  File "/usr/lib64/python3.5/site-packages/sklearn/base.py", line 12, in <module>
    from .utils.fixes import signature
  File "/usr/lib64/python3.5/site-packages/sklearn/utils/__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "/usr/lib64/python3.5/site-packages/sklearn/utils/validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "/usr/lib64/python3.5/site-packages/sklearn/utils/fixes.py", line 403, in <module>
    from scipy.stats import rankdata
  File "/usr/lib64/python3.5/site-packages/scipy/stats/__init__.py", line 343, in <module>
    from .stats import *
  File "/usr/lib64/python3.5/site-packages/scipy/stats/stats.py", line 171, in <module>
    from . import distributions
  File "/usr/lib64/python3.5/site-packages/scipy/stats/distributions.py", line 10, in <module>
    from ._distn_infrastructure import (entropy, rv_discrete, rv_continuous,
  File "/usr/lib64/python3.5/site-packages/scipy/stats/_distn_infrastructure.py", line 16, in <module>
    from scipy.misc import doccer
  File "/usr/lib64/python3.5/site-packages/scipy/misc/__init__.py", line 67, in <module>
    from scipy.interpolate._pade import pade as _pade
  File "/usr/lib64/python3.5/site-packages/scipy/interpolate/__init__.py", line 175, in <module>
    from .interpolate import *
  File "/usr/lib64/python3.5/site-packages/scipy/interpolate/interpolate.py", line 32, in <module>
    from .interpnd import _ndim_coords_from_arrays
  File "interpnd.pyx", line 1, in init scipy.interpolate.interpnd
  File "/usr/lib64/python3.5/site-packages/scipy/spatial/__init__.py", line 95, in <module>
    from .qhull import *
  File "qhull.pyx", line 2155, in init scipy.spatial.qhull
AttributeError: 'cython_function_or_method' object has no attribute '__func__'
```

This happens with the current HEAD (see above) as well as with all releases I have tried out (`0.3.1`,`0.2.6`,`0.2.5`).

This may not be an intrinsic nilearn issue, since this has only recently started happening (older versions - `0.2.*` have installed fine for me in the past), but I am hoping maybe you can help me trace the cause of this.

**Comment by GaelVaroquaux** [comment]
Your scipy install seems broken

⁣Sent from my phone. Please forgive typos and briefness.​

**Comment by TheChymera** [comment]
I tried rebuilding scipy, and cython, and numpy  --- and none of it helped. Are there perhaps any scipy dependencies which I should try to rebuild?

**Comment by archenroot** [comment]
in same shit....

**Comment by jeromedockes** [comment]
seems to be related to https://github.com/scipy/scipy/issues/8562, https://github.com/cython/cython/issues/2154 . I believe if you try to run the scipy test suite it will fail on your environment; you probably need to upgrade either scipy or Cython.

**Comment by archenroot** [comment]
Compilation of all mentioned packages to latest available versions in progress.

**Comment by archenroot** [comment]
Ok, when on:
```
[ebuild   R   ~] dev-python/cython-0.29.7::gentoo  USE="-doc -emacs -test" PYTHON_TARGETS="python2_7 python3_6 -python3_5 -python3_7" 0 KiB
[ebuild   R   ~] dev-python/numpy-1.16.1::gentoo  USE="lapack -doc -test" PYTHON_TARGETS="python2_7 python3_6 -python3_5 -python3_7" 0 KiB
[ebuild   R    ] sci-libs/scipy-1.1.0::gentoo  USE="-doc -sparse -test" PYTHON_TARGETS="python2_7 python3_6 -python3_5 -python3_7" 0 KiB

```
The error is gone. Althoght these are marked as unstable versions from Gentoo perspective, but in some cases Gentoo need too much time to mark as stable..

**Comment by TheChymera** [comment]
@archenroot thank you for posting here, I too can confirm that this issue is resolved with the newest versions. Generally I would recommend adding `~amd64` to your keywords if you plan to use a lot of scientific software.

While it may be wholly unrelated, “broken scipy” occasionally crops up due to the [BLAS/LAPACK fiasco](https://github.com/gentoo/sci/issues/805), which we almost fixed, but then the developer regequit. If you are interested in giving us a hand with this, I can try and provide more details in the relevant issue.
