### ISSUE TITLE
MemoryError while masking timecourse file using a mask at a higher resolution

### ISSUE THREAD

**Issue by TheChymera** [nilearn/nilearn#1883]
I keep my brain regions files at the highest resolution in order to not lose information, however my fMRI timecourse data is at a lower resolution. I am trying to take the `nibabel.Nifti1Image` object of the mask and apply it to the timecourse file, like so:

```python
masker = nilearn.input_data.NiftiMasker(mask_img=roi)
final_time_series = masker.fit_transform(ts_file)
final_time_series = final_time_series.T
final_time_series = np.mean(final_time_series, axis=0)
```

I get the following traceback:

```
Failed to import duecredit due to No module named 'duecredit'
/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_gtk3.py:32: DeprecationWarning: Gdk.Cursor.new is deprecated
  cursors.MOVE          : Gdk.Cursor.new(Gdk.CursorType.FLEUR),
/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_gtk3.py:172: DeprecationWarning: Gtk.Widget.set_double_buffered is deprecated
  self.set_double_buffered(True)
/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_gtk3.py:339: DeprecationWarning: Gtk.Window.set_wmclass is deprecated
  self.window.set_wmclass("matplotlib", "Matplotlib")
/usr/lib64/python3.6/site-packages/matplotlib/backends/backend_gtk3.py:372: DeprecationWarning: Gtk.Widget.size_request is deprecated
  size_request = child.size_request()
/usr/lib64/python3.6/site-packages/nilearn/_utils/cache_mixin.py:232: DeprecationWarning: The 'cachedir' attribute has been deprecated in version 0.12 and will be removed in version 0.14.
Use os.path.join(memory.location, 'joblib') attribute instead.
  if (memory.cachedir is None and memory_level is not None
Traceback (most recent call last):
  File "ts.py", line 38, in <module>
    roi=my_roi,
  File "/home/chymera/src/SAMRI/samri/plotting/timeseries.py", line 119, in roi_based
    final_time_series = masker.fit_transform(ts_file)
  File "/usr/lib64/python3.6/site-packages/nilearn/input_data/base_masker.py", line 207, in fit_transform
    return self.fit(**fit_params).transform(X, confounds=confounds)
  File "/usr/lib64/python3.6/site-packages/nilearn/input_data/base_masker.py", line 177, in transform
    return self.transform_single_imgs(imgs, confounds)
  File "/usr/lib64/python3.6/site-packages/nilearn/input_data/nifti_masker.py", line 307, in transform_single_imgs
    dtype=self.dtype
  File "/usr/lib64/python3.6/site-packages/joblib/memory.py", line 322, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/nilearn/input_data/nifti_masker.py", line 55, in filter_and_mask
    dtype=dtype)
  File "/usr/lib64/python3.6/site-packages/nilearn/input_data/base_masker.py", line 85, in filter_and_extract
    copy=copy)
  File "/usr/lib64/python3.6/site-packages/joblib/memory.py", line 322, in __call__
    return self.func(*args, **kwargs)
  File "/usr/lib64/python3.6/site-packages/nilearn/image/resampling.py", line 531, in resample_img
    order=order, dtype=resampled_data_dtype)
MemoryError
```

I have tried to monitor the memory usage via `top` and it actually does not seem to go over 30% so I have no idea what's up here. Maybe some joblib magick?
At any rate, this is solved if I save the file to disk and downsample it with ANTs.
In the absence of this “just working” do you know if I can use nilearn to easily resample an image at the resolution of another image provided they are in the same space (i.e. no intricate registration needed)?

**Comment by TheChymera** [comment]
Hm, I have just discovered the `target_affine` parameter, and it seems to do the trick. Is this an adequate solution? why doesn't this happen automatically upon mask application?

```
masker = NiftiMasker(mask_img=roi, target_affine=ts_file.affine)
final_time_series = masker.fit_transform(ts_file)
final_time_series = final_time_series.T
final_time_series = np.mean(final_time_series, axis=0)
```

**Comment by bthirion** [comment]
I believe that the `roi` you're using has an extreme resolution. But if you don't worry about having voxel-level correspondences between your final_time_series and the provided roi, the solution with `target_affine` is fine. An alternative is to resample initially the input roi image.

**Comment by GaelVaroquaux** [comment]
We should probably document this option better.

A pull request to the doc / docstring discussing this in a way that you
find clear would be most welcomed. Thanks!

**Comment by TheChymera** [comment]
How would you define “extreme resolution”? Does nilearn have any hard-coded resolution cutoffs at which it throws in the towel? What I find worrying is that it gives me a memory error when upwards of 70% of my mem is still available.

It's also not an issue of threads, since it runs single-threaded.

**Comment by man-shu** [comment]
I think the MemoryError could be related to #1754, if your img is big enough :

> In terms of time, where it takes a lot is at resampling step, in particular when resampling_target='maps' or 'mask', it resamples all the 15k images to maps image or mask image.

because NiftiMasker always resamples the img -> mask, and you cannot resample mask -> img.

Is there a specific reason for not having a `resampling_target` parameter in NiftiMasker as in [NiftiMapsMasker](https://nilearn.github.io/dev/modules/generated/nilearn.maskers.NiftiMapsMasker.html) and [NiftiLabelsMasker](https://nilearn.github.io/dev/modules/generated/nilearn.maskers.NiftiLabelsMasker.html) @bthirion ?

**Comment by bthirion** [comment]
No, I think its' simply historical.
