### ISSUE TITLE
Building documentation > Sphinx 2.0.0

### ISSUE THREAD

**Issue by KamalakerDadi** [nilearn/nilearn#1976]
May be we will see some issues building documentation using Sphinx > 2.0.0 since it is dropped support for Python2. Because doc/conf.py is not compatible to Python3. If I am not wrong.

Either we force to install sphinx==1.8.5 until we drop support to Python2 or make conf.py compatible to both Python2 and 3.

```python
Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/home/kdadi/.local/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 74, in execfile_
    code = compile(source, filepath_enc, 'exec')
  File "/home/kdadi/dev/nilearn/doc/conf.py", line 231
    ur"""Ga\xebl Varoquaux and Alexandre Abraham"""
                                               ^
SyntaxError: invalid syntax

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/kdadi/.local/lib/python3.6/site-packages/sphinx/config.py", line 361, in eval_config_file
    execfile_(filename, namespace)
  File "/home/kdadi/.local/lib/python3.6/site-packages/sphinx/util/pycompat.py", line 85, in execfile_
    filepath)
  File "/usr/lib/python3.6/logging/__init__.py", line 1642, in warning
    self.log(WARNING, msg, *args, **kwargs)
  File "/home/kdadi/.local/lib/python3.6/site-packages/sphinx/util/logging.py", line 126, in log
    super().log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1674, in log
    self.logger.log(level, msg, *args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1374, in log
    self._log(level, msg, args, **kwargs)
  File "/usr/lib/python3.6/logging/__init__.py", line 1444, in _log
    self.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1454, in handle
    self.callHandlers(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 1516, in callHandlers
    hdlr.handle(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 861, in handle
    rv = self.filter(record)
  File "/usr/lib/python3.6/logging/__init__.py", line 720, in filter
    result = f.filter(record)
  File "/home/kdadi/.local/lib/python3.6/site-packages/sphinx/util/logging.py", line 428, in filter
    raise SphinxWarning(message)
sphinx.errors.SphinxWarning: Support for evaluating Python 2 syntax is deprecated and will be removed in Sphinx 4.0. Convert /home/kdadi/dev/nilearn/doc/conf.py to Python 3 syntax.

make[1]: *** [Makefile:157: check] Error 2
make[1]: Leaving directory '/home/kdadi/dev/nilearn/doc'
make: *** [Makefile:68: html-strict] Error 2

```

**Comment by kchawla-pi** [comment]
When I do a conda list, I get sphinx version as 1.8.2 with python 3.6 . 
Also this is weird, I wasn't getting this on circleci or my local builds.
Whats the version when you do conda list?

**Comment by kchawla-pi** [comment]
@KamalakerDadi If you have encountered this issue, please tell me now. I don't see it on my local builds and I can't trust circleci servers right now.

**Comment by KamalakerDadi** [comment]
> Whats the version when you do conda list?

I don't have conda installed on my laptop. I changed my laptop recently.

**Comment by kchawla-pi** [comment]
OKay, however you ran the above snippet, what are the versions installed?
Can you install conda and try with that?

**Comment by KamalakerDadi** [comment]
This issue I have posted for being aware of.

>OKay, however you ran the above snippet, what are the versions installed?

As I said, sphinx=2.0.0 is what you required to reproduce.

**Comment by kchawla-pi** [comment]
> This issue I have posted for being aware of.

Ah okay, I thought you were mentioning a more immediate problem. Thanks!

**Comment by KamalakerDadi** [comment]
conda is now picking up latest version of sphinx. FYI.
As it can be seen here https://circleci.com/gh/nilearn/nilearn/4102?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

PR #2005

**Comment by kchawla-pi** [comment]
Will work on this today
