### ISSUE TITLE
Error while calling plotting.plot_connectome

### ISSUE THREAD

**Issue by wingedRuslan** [nilearn/nilearn#2113]
- What version of Nilearn are you using?
**0.5.2**
- What were you trying to do?
plot the connectome with the input data I included in the issue below 
- What did you expect will happen?
plotted connectome
- What actually happened?
Error while calling the function

While calling the `nilearn.plotting.plot_connectome` I get this error:

<details><summary>Error - Only length-1 arrays can be converted to Python scalars</summary>

```
-----------------------------------------------------------------------
TypeError                             Traceback (most recent call last)
<ipython-input-12-45652bd6e869> in <module>()
----> 1 foo.plot_connectome_with_nilearn(G01)

~/GSoC/scona/scona/visualisations.py in plot_connectome_with_nilearn(G)
    519 
    520     plotting.plot_connectome(
--> 521         adj_matrix, node_coords)

~/anaconda3/lib/python3.6/site-packages/nilearn/plotting/img_plotting.py in plot_connectome(adjacency_matrix, node_coords, node_color, node_size, edge_cmap, edge_vmin, edge_vmax, edge_threshold, output_file, display_mode, figure, axes, title, annotate, black_bg, alpha, edge_kwargs, node_kwargs, colorbar)
   1283                       edge_threshold=edge_threshold,
   1284                       edge_kwargs=edge_kwargs, node_kwargs=node_kwargs,
-> 1285                       colorbar=colorbar)
   1286 
   1287     if output_file is not None:

~/anaconda3/lib/python3.6/site-packages/nilearn/plotting/displays.py in add_graph(self, adjacency_matrix, node_coords, node_color, node_size, edge_cmap, edge_vmin, edge_vmax, edge_threshold, edge_kwargs, node_kwargs, colorbar)
   1834                 ax._add_lines(line_coords, adjacency_matrix_values, edge_cmap,
   1835                               vmin=edge_vmin, vmax=edge_vmax,
-> 1836                               **edge_kwargs)
   1837             # To obtain the brain left view, we simply invert the x axis
   1838             if ax.direction == 'l':

~/anaconda3/lib/python3.6/site-packages/nilearn/plotting/displays.py in _add_lines(self, line_coords, line_values, cmap, vmin, vmax, **kwargs)
    499             this_kwargs.update(kwargs)
    500             xdata, ydata = start_end_point_2d.T
--> 501             line = lines.Line2D(xdata, ydata, **this_kwargs)
    502             self.ax.add_line(line)
    503 

~/anaconda3/lib/python3.6/site-packages/matplotlib/lines.py in __init__(self, xdata, ydata, linewidth, linestyle, color, marker, markersize, markeredgewidth, markeredgecolor, markerfacecolor, markerfacecoloralt, fillstyle, antialiased, dash_capstyle, solid_capstyle, dash_joinstyle, solid_joinstyle, pickradius, drawstyle, markevery, **kwargs)
    396         self.set_linestyle(linestyle)
    397         self.set_drawstyle(drawstyle)
--> 398         self.set_linewidth(linewidth)
    399 
    400         self._color = None

~/anaconda3/lib/python3.6/site-packages/matplotlib/lines.py in set_linewidth(self, w)
   1004         ACCEPTS: float value in points
   1005         """
-> 1006         w = float(w)
   1007 
   1008         if self._linewidth != w:

~/anaconda3/lib/python3.6/site-packages/numpy/ma/core.py in __float__(self)
   4294         """
   4295         if self.size > 1:
-> 4296             raise TypeError("Only length-1 arrays can be converted "
   4297                             "to Python scalars")
   4298         elif self._mask:

TypeError: Only length-1 arrays can be converted to Python scalars

```
</details>

Here is the required input data to reproduce the error:
[input_nilearn.zip](https://github.com/nilearn/nilearn/files/3445883/input_nilearn.zip)

Here are steps how I got the input data:  
```
import numpy as np
import networkx as nx

from nilearn import plotting

# Return the graph adjacency matrix as a NumPy matrix.
adjacency_matrix = nx.convert_matrix.to_numpy_matrix(G)

# adjacency_matrix.shape -> (308,308)

# store nodes coordinates in NumPy array
node_coords = np.array([G.node[node]["centroids"] for node in G.nodes()])

# node_coords.shape -> (308,3)

plotting.plot_connectome(adjacency_matrix, node_coords)
```
where G is a Networkx.Graph

<details><summary>My unsuccessful attempts to solve</summary>

1) Reduce the number of nodes to 10 and keep the edges only between those nodes.
```
W = G01.subgraph([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
adj_mat = nx.convert_matrix.to_numpy_matrix(W)
node_coords = np.array([W.node[node]["centroids"] for node in [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]])
plotting.plot_connectome(adj_mat, node_coords)
```
2) In the error message this part  looks suspicious:  
    396         self.set_linestyle(linestyle)
    397         self.set_drawstyle(drawstyle)
--> 398         self.set_linewidth(linewidth)
    399 
    400         self._color = None

So while calling the function, I explicitly indicated the linewidth in **kwargs parameter  
```
edge_kwargs = {}
edge_kwargs["linewidth"] = 1.

plotting.plot_connectome(adj_mat, node_coords, edge_kwargs=edge_kwargs)
```

<details><summary>And got another error:</summary>

```
ValueError                            Traceback (most recent call last)
~/anaconda3/lib/python3.6/site-packages/IPython/core/formatters.py in __call__(self, obj)
    330                 pass
    331             else:
--> 332                 return printer(obj)
    333             # Finally look for special method names
    334             method = get_real_method(obj, self.print_method)

~/anaconda3/lib/python3.6/site-packages/IPython/core/pylabtools.py in <lambda>(fig)
    235 
    236     if 'png' in formats:
--> 237         png_formatter.for_type(Figure, lambda fig: print_figure(fig, 'png', **kwargs))
    238     if 'retina' in formats or 'png2x' in formats:
    239         png_formatter.for_type(Figure, lambda fig: retina_figure(fig, **kwargs))

~/anaconda3/lib/python3.6/site-packages/IPython/core/pylabtools.py in print_figure(fig, fmt, bbox_inches, **kwargs)
    119 
    120     bytes_io = BytesIO()
--> 121     fig.canvas.print_figure(bytes_io, **kw)
    122     data = bytes_io.getvalue()
    123     if fmt == 'svg':

~/anaconda3/lib/python3.6/site-packages/matplotlib/backend_bases.py in print_figure(self, filename, dpi, facecolor, edgecolor, orientation, format, **kwargs)
   2206                     orientation=orientation,
   2207                     dryrun=True,
-> 2208                     **kwargs)
   2209                 renderer = self.figure._cachedRenderer
   2210                 bbox_inches = self.figure.get_tightbbox(renderer)

~/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in print_png(self, filename_or_obj, *args, **kwargs)
    505 
    506     def print_png(self, filename_or_obj, *args, **kwargs):
--> 507         FigureCanvasAgg.draw(self)
    508         renderer = self.get_renderer()
    509         original_dpi = renderer.dpi

~/anaconda3/lib/python3.6/site-packages/matplotlib/backends/backend_agg.py in draw(self)
    428             if toolbar:
    429                 toolbar.set_cursor(cursors.WAIT)
--> 430             self.figure.draw(self.renderer)
    431         finally:
    432             if toolbar:

~/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

~/anaconda3/lib/python3.6/site-packages/matplotlib/figure.py in draw(self, renderer)
   1293 
   1294             mimage._draw_list_compositing_images(
-> 1295                 renderer, self, artists, self.suppressComposite)
   1296 
   1297             renderer.close_group('figure')

~/anaconda3/lib/python3.6/site-packages/matplotlib/image.py in _draw_list_compositing_images(renderer, parent, artists, suppress_composite)
    136     if not_composite or not has_images:
    137         for a in artists:
--> 138             a.draw(renderer)
    139     else:
    140         # Composite any adjacent images together

~/anaconda3/lib/python3.6/site-packages/matplotlib/artist.py in draw_wrapper(artist, renderer, *args, **kwargs)
     53                 renderer.start_filter()
     54 
---> 55             return draw(artist, renderer, *args, **kwargs)
     56         finally:
     57             if artist.get_agg_filter() is not None:

~/anaconda3/lib/python3.6/site-packages/matplotlib/axes/_base.py in draw(self, renderer, inframe)
   2372             artists = [a for a in artists
   2373                        if not a.get_animated() or a in self.images]
-> 2374         artists = sorted(artists, key=attrgetter('zorder'))
   2375 
   2376         # rasterize artists with negative zorder

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

<matplotlib.figure.Figure at 0x7f5fa56f3278>

```
</details>

</details>

If you have any questions feel free to ask and I will gladly answer!

**Comment by bthirion** [comment]
Thx for reporting.
@kchawla-pi can you reproduce it ?

**Comment by jeromedockes** [comment]
it is because you provide a `np.matrix` for the adjacency matrix rather than a `np.array`. use `nx.convert_matrix.to_numpy_array` rather than `nx.convert_matrix.to_numpy_matrix`

**Comment by jeromedockes** [comment]
```python
>>> import numpy as np
>>> from nilearn import plotting
>>> coord = np.random.randn(4, 3) * 10                                                                                                  
>>> adj = np.random.binomial(1, .2, size=(4, 4))                                                                                        
>>> adj = adj | adj.T                                                                                                                   
>>> plotting.plot_connectome(adj, coord)                                                                                                
<nilearn.plotting.displays.OrthoProjector object at 0x7fb867364390>
>>> plotting.plot_connectome(np.matrix(adj), coord)                                                                                     
Traceback (most recent call last):
  File "<ipython-input-37-5a72a9fc2383>", line 1, in <module>
    plotting.plot_connectome(np.matrix(adj), coord)
  File "/home/jerome/workspace/nilearn/nilearn/plotting/img_plotting.py", line 1285, in plot_connectome
    colorbar=colorbar)
  File "/home/jerome/workspace/nilearn/nilearn/plotting/displays.py", line 1838, in add_graph
    **edge_kwargs)
  File "/home/jerome/workspace/nilearn/nilearn/plotting/displays.py", line 501, in _add_lines
    line = lines.Line2D(xdata, ydata, **this_kwargs)
  File "/home/jerome/.virtualenvs/py3.7/lib/python3.7/site-packages/matplotlib/lines.py", line 376, in __init__
    self.set_linewidth(linewidth)
  File "/home/jerome/.virtualenvs/py3.7/lib/python3.7/site-packages/matplotlib/lines.py", line 1103, in set_linewidth
    w = float(w)
  File "/home/jerome/.virtualenvs/py3.7/lib/python3.7/site-packages/numpy/ma/core.py", line 4296, in __float__
    raise TypeError("Only length-1 arrays can be converted "
TypeError: Only length-1 arrays can be converted to Python scalars

>>>  
```

**Comment by wingedRuslan** [comment]
@jeromedockes thanks for the help! You are totally right. 

Closing issue

**Comment by jeromedockes** [comment]
thanks @wingedRuslan !
