### ISSUE TITLE
canica.fit() could not return result

### ISSUE THREAD

**Issue by alienx-zero** [nilearn/nilearn#2568]
Hi, dear all, I am following the guide: https://nilearn.github.io/auto_examples/03_connectivity/plot_compare_decomposition.html#sphx-glr-auto-examples-03-connectivity-plot-compare-decomposition-py
Here is the code:
```# -*- coding: utf-8 -*-
"""
Created on Sat Sep 19 17:55:29 2020

@author: 99488
"""

from nilearn import datasets

rest_dataset = datasets.fetch_development_fmri(n_subjects=30)
func_filenames = rest_dataset.func  # list of 4D nifti files for each subject

# print basic information on the dataset
print('First functional nifti image (4D) is at: %s' %
      rest_dataset.func[0])  # 4D data

from nilearn.decomposition import CanICA

canica = CanICA(n_components=20,
                memory="nilearn_cache", memory_level=2,
                verbose=10,
                mask_strategy='template',
                random_state=0)
canica.fit(func_filenames)

# Retrieve the independent components in brain space. Directly
# accesible through attribute `components_img_`.
canica_components_img = canica.components_img_
# components_img is a Nifti Image object, and can be saved to a file with
# the following line:
canica_components_img.to_filename('canica_resting_state.nii.gz')
```

However, when I run to this sentence:
```canica.fit(func_filenames)```
it raise error.
Here is the error info:
```runfile('E:/OPT/research/fMRI/fMRI_ICA.py', wdir='E:/OPT/research/fMRI')
First functional nifti image (4D) is at: C:\Users\99488/nilearn_data\development_fmri\development_fmri\sub-pixar123_task-pixar_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz
[MultiNiftiMasker.fit] Loading data from [C:\Users\99488/nilearn_data\development_fmri\development_fmri\sub-pixar123_task-pixar_space-MNI152NLin2009cAsym_desc-preproc_bold.nii.gz, C:\Users\99488/nilearn_data\development_fmri\development_fmri
[MultiNiftiMasker.fit] Computing mask
Template mask computation
Traceback (most recent call last):

  File "E:\OPT\research\fMRI\fMRI_ICA.py", line 24, in <module>
    canica.fit(func_filenames)

  File "C:\Users\99488\AppData\Roaming\Python\Python37\site-packages\nilearn\decomposition\base.py", line 396, in fit
    self.masker_.fit(imgs)

  File "C:\Users\99488\AppData\Roaming\Python\Python37\site-packages\nilearn\input_data\multi_nifti_masker.py", line 208, in fit
    **mask_args)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\memory.py", line 565, in __call__
    return self._cached_call(args, kwargs)[0]

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\memory.py", line 531, in _cached_call
    out, metadata = self.call(*args, **kwargs)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\memory.py", line 727, in call
    output = self.func(*args, **kwargs)

  File "C:\Users\99488\AppData\Roaming\Python\Python37\site-packages\nilearn\masking.py", line 659, in compute_multi_gray_matter_mask
    memory=memory, verbose=verbose)

  File "C:\Users\99488\AppData\Roaming\Python\Python37\site-packages\nilearn\masking.py", line 577, in compute_gray_matter_mask
    resampled_template = cache(resample_to_img, memory)(template, target_img)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\memory.py", line 565, in __call__
    return self._cached_call(args, kwargs)[0]

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\memory.py", line 480, in _cached_call
    func_id, args_id = self._get_output_identifiers(*args, **kwargs)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\memory.py", line 586, in _get_output_identifiers
    argument_hash = self._get_argument_hash(*args, **kwargs)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\memory.py", line 581, in _get_argument_hash
    coerce_mmap=(self.mmap_mode is not None))

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 261, in hash
    return hasher.hash(obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 63, in hash
    self.dump(obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 437, in dump
    self.save(obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 236, in save
    Hasher.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 140, in _batch_setitems
    Pickler._batch_setitems(self, iter(sorted(items)))

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 885, in _batch_setitems
    save(v)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 236, in save
    Hasher.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 662, in save_reduce
    save(state)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 236, in save
    Hasher.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 140, in _batch_setitems
    Pickler._batch_setitems(self, iter(sorted(items)))

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 885, in _batch_setitems
    save(v)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 236, in save
    Hasher.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 662, in save_reduce
    save(state)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 236, in save
    Hasher.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 140, in _batch_setitems
    Pickler._batch_setitems(self, iter(sorted(items)))

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 885, in _batch_setitems
    save(v)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 236, in save
    Hasher.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 662, in save_reduce
    save(state)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 236, in save
    Hasher.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 140, in _batch_setitems
    Pickler._batch_setitems(self, iter(sorted(items)))

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 885, in _batch_setitems
    save(v)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 236, in save
    Hasher.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib\hashing.py", line 89, in save
    Pickler.save(self, obj)

  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\pickle.py", line 524, in save
    rv = reduce(self.proto)

  File "indexed_gzip\indexed_gzip.pyx", line 956, in indexed_gzip.indexed_gzip.IndexedGzipFile.__reduce__

  File "indexed_gzip\indexed_gzip.pyx", line 737, in indexed_gzip.indexed_gzip._IndexedGzipFile.export_index

AttributeError: '_io.BytesIO' object has no attribute 'mode'```
How to fix it? Thanks for all solutions

**Comment by alienx-zero** [comment]
It is fixed when I switch to another conda environment...But still I do not know why it do not work here. I guess it is conflicted with some py file?

**Comment by bthirion** [comment]
I think that the file you use as input is corrupted. Cna you try and open it with your preferred viewer, and if spits an error, redo data download ?
Best,

**Comment by alienx-zero** [comment]
@bthirion thanks for reply. I do not think it is because of data, since when I run same code in another other anaconda environment, it works. I think it should be incompatible to some py. file..

**Comment by thomasbazeille** [comment]
Hello ! Which version of Nilearn are you using ?

**Comment by emdupre** [comment]
> Which version of Nilearn are you using ?

+1 on this question. One other idea: I wonder if your cache is what's causing the problem. In particular, I'm not sure if the `joblib` package in the `tensorflow`_13` conda environment has access to the `nilearn_cache` folder. Interestingly, `nilearn` seems to be in a different environment, see (modified from above):

```
  File "C:\Users\99488\AppData\Roaming\Python\Python37\site-packages\nilearn\
  File "D:\Users\99488\Anaconda3\envs\tensorflow1_13\lib\site-packages\joblib
```

One quick way to check this would be to rerun but set `memory=None` when instantiating `CanICA`.

**Comment by AlexandreAbraham** [comment]
The question would be, what version of Python are you using? It looks like a problem directly inside Gzip.

Let me explain. The lines where the problem happens are

File "indexed_gzip\indexed_gzip.pyx", line 956, in indexed_gzip.indexed_gzip.IndexedGzipFile.__reduce__
```python
        if fobj.npoints > 0:
            index = io.BytesIO()
            self.export_index(fileobj=index)
```

File "indexed_gzip\indexed_gzip.pyx", line 737, in indexed_gzip.indexed_gzip._IndexedGzipFile.export_index
```python
            if fileobj.mode != 'wb':
                raise ValueError(
                    'File should be opened write-only binary mode.')
```

A BytesIO object is created but this has no mode. You can check it in an interactive python:
```
Python 3.7.3 (default, Mar 27 2019, 16:54:48) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.6.1 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import io                                                                                                                                                                                                                             

In [2]: io.BytesIO().mode                                                                                                                                                                                                                     
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-2-851e60841292> in <module>
----> 1 io.BytesIO().mode
```

However, I am able to write in a BytesIO on my machine. I guess you are not supposed to get into this part of the code with a BytesIO. This is very weird but I doubt that it has any link with nilearn.

**Comment by bthirion** [comment]
Any update on this issue ?

**Comment by bona3476** [comment]
!pip uninstall indexed_gzip --yes

worked for me
