### ISSUE TITLE
Using custom response functions for computing GLM leads to SyntaxError when computing contrasts

### ISSUE THREAD

**Issue by alexisthual** [nilearn/nilearn#3024]
The bugfix introduced in #3018 derives names of the `design_matrices_` attribute of `FirstLevelModel`. However, computed names contain spaces, which later on raises errors.
In particular, when trying to compute contrasts (or generate reports) using the `"condition_1-condition_2"` string syntax, `pandas` fails to evaluate it and raises a `SyntaxError`.

Nilearn version: 0.8.2.dev

### Expected behavior
It should work without error.

### Actual behavior
It fails with a `SyntaxError`:

```
/storage/store2/work/athual/repo/nilearn/nilearn/plotting/matrix_plotting.py:296: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all axes decorations. 
  plt.tight_layout()
/storage/store2/work/athual/repo/nilearn/nilearn/reporting/utils.py:9: UserWarning: Tight layout not applied. The bottom and top margins cannot be made large enough to accommodate all axes decorations. 
  io_buffer, format="svg", facecolor="white", edgecolor="white"
Traceback (most recent call last):

  File "/storage/store2/work/athual/anaconda3/envs/singbrain/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3444, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "/tmp/ipykernel_44279/1486762308.py", line 10, in <module>
    bg_img=anatomical_img,

  File "/storage/store2/work/athual/repo/nilearn/nilearn/glm/_base.py", line 117, in generate_report
    report_dims=report_dims)

  File "/storage/store2/work/athual/repo/nilearn/nilearn/reporting/glm_reporter.py", line 202, in make_glm_report
    contrast_plots = _plot_contrasts(contrasts, design_matrices)

  File "/storage/store2/work/athual/repo/nilearn/nilearn/reporting/glm_reporter.py", line 365, in _plot_contrasts
    colorbar=True)

  File "/storage/store2/work/athual/repo/nilearn/nilearn/plotting/matrix_plotting.py", line 273, in plot_contrast_matrix
    contrast_def, design_column_names)

  File "/storage/store2/work/athual/repo/nilearn/nilearn/glm/contrasts.py", line 43, in expression_to_contrast_vector
    contrast_vector = df.eval(expression, engine="python").values

  File "/storage/store2/work/athual/anaconda3/envs/singbrain/lib/python3.7/site-packages/pandas/core/frame.py", line 4191, in eval
    return _eval(expr, inplace=inplace, **kwargs)

  File "/storage/store2/work/athual/anaconda3/envs/singbrain/lib/python3.7/site-packages/pandas/core/computation/eval.py", line 348, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)

  File "/storage/store2/work/athual/anaconda3/envs/singbrain/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 806, in __init__
    self.terms = self.parse()

  File "/storage/store2/work/athual/anaconda3/envs/singbrain/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 825, in parse
    return self._visitor.visit(self.expr)

  File "/storage/store2/work/athual/anaconda3/envs/singbrain/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 407, in visit
    raise e

  File "/storage/store2/work/athual/anaconda3/envs/singbrain/lib/python3.7/site-packages/pandas/core/computation/expr.py", line 403, in visit
    node = ast.fix_missing_locations(ast.parse(clean))

  File "/storage/store2/work/athual/anaconda3/envs/singbrain/lib/python3.7/ast.py", line 35, in parse
    return compile(source, filename, mode, PyCF_ONLY_AST)

  File "<unknown>", line 1
    audio mion_rf -control_visual_audio mion_rf
                ^
SyntaxError: invalid syntax
```

### Steps and code to reproduce bug

I won't give a fully operational code snippet, but given that one already has functional images, experiment events and a custom rf_model, the following code will raise the error :

```python
fmri_glm = FirstLevelModel(
    t_r=t_r,
    noise_model="ar1",
    standardize=False,
    hrf_model=rf_model,
)

fmri_glm.fit(functional_img, events)

fmri_glm.generate_report(["condition_1 hrf_model-condition_2 hrf_model"])
```

### Fix

A quick fix would be to simple replace spaces with underscores. I'll write a PR for that.

**Comment by NicolasGensollen** [comment]
Great! Thanks for working on this @alexisthual !
