### ISSUE TITLE
Can't run TFCE=True in non_parametric_inference

### ISSUE THREAD

**Issue by andreifoldes** [nilearn/nilearn#3583]
I tried running a paired t-test with the following design matrix:
![image](https://user-images.githubusercontent.com/7458009/224086234-0ccaba86-4a6a-4b29-a4d3-9b2f79cf26ae.png)

```
    out_dict = non_parametric_inference(
        second_level_input,
        design_matrix=paired_design_matrix,
        model_intercept=True,
        second_level_contrast=('H1 vs H2'),
        mask=mask_img,
        n_perm=10000,  # 500 for the sake of time. Ideally, this should be 10,000.
        two_sided_test=True,
        n_jobs=-1,
        threshold=0.005,
        verbose=1,
        tfce=(True)
    )
```

It works fine with TFCE=False.

Nilearn version: 
0.10

### Actual behavior

but got ..

```
  File "/tmp/ipykernel_30398/1507163694.py", line 5, in <cell line: 5>
    out_dict = non_parametric_inference(

  File "/home/saptaf1/anaconda3/envs/spyder-env/lib/python3.8/site-packages/nilearn/glm/second_level/second_level.py", line 854, in non_parametric_inference
    outputs = permuted_ols(

  File "/home/saptaf1/anaconda3/envs/spyder-env/lib/python3.8/site-packages/nilearn/mass_univariate/permuted_least_squares.py", line 778, in permuted_ols
    tfce_original_data = _calculate_tfce(

  File "/home/saptaf1/anaconda3/envs/spyder-env/lib/python3.8/site-packages/nilearn/mass_univariate/_utils.py", line 86, in _calculate_tfce
    score_threshs = np.arange(step, max_score + step, step)

ValueError: arange: cannot compute length
```

**Comment by bthirion** [comment]
Thx for reporting. Is there any chance you can share the images used ? Can you reproduce this behavior with the dataset in https://nilearn.github.io/stable/auto_examples/05_glm_second_level/plot_second_level_two_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-two-sample-test-py  ?

**Comment by Remi-Gau** [comment]
I tried to add the following in this example and it worked fine:

```python
non_parametric_inference(
    second_level_input,
    design_matrix=paired_design_matrix,
    model_intercept=True,
    second_level_contrast=("vertical vs horizontal"),
    n_perm=28,  # 500 for the sake of time. Ideally, this should be 10,000.
    two_sided_test=True,
    n_jobs=-1,
    threshold=0.005,
    verbose=1,
    tfce=(True)
)
```

**Comment by YukunQu** [comment]
> Thx for reporting. Is there any chance you can share the images used ? Can you reproduce this behavior with the dataset in https://nilearn.github.io/stable/auto_examples/05_glm_second_level/plot_second_level_two_sample_test.html#sphx-glr-auto-examples-05-glm-second-level-plot-second-level-two-sample-test-py ?

I also meet this problem. And the bug seems it depend on the number of permutation. If I set n_perm to a small value(like 100-500.) Nothings error append. But When I set to 5000 ~ 10000. The error emerged.

**Comment by YukunQu** [comment]
I also meet this problem and it seem depend the number of permutation of tfce. when I set small n_perm value, it didn't appear.

**Comment by bthirion** [comment]
I've run the above examples with 5000 permutations and did not hit an issue. Could this be a memory problem ?

**Comment by YukunQu** [comment]
> I've run the above examples with 5000 permutations and did not hit an issue. Could this be a memory problem ?

Maybe I know the reason for this issue. I use a mask to perform non-parametric inference with tfce. The mask has 3722 voxels. When I set the number of permutations to less than this number, the function works well. But if the number of permutations is greater than 3722, it reports this error: "ValueError: arange: cannot compute length".

 I still haven't figured out what causes the bug, but perhaps your team can help identify the issue."

**Comment by eilidhmacnicol** [comment]
Hi! Just wanted to add to this thread because I have also come across this bug, but only in some image modalities and not others.

I am running non-parametric inference to generate p-value images for two continuous covariates (first for $x$ and then for $x^2$) for a given design matrix with array jobs submitted as a batch. 

Each job is submitted with the same template-space mask supplied and the default 10,000 permutations but the `second_level_input` changes depending on the SLURM task ID (so this obviously also means that the design matrix is slightly different too). The inputs are either TBM (i.e. log Jacobian Determinant) or VBM (i.e. GM volumes). The TBM tasks successfully complete but the VBM crash with the trace:

```
[non_parametric_inference] 
Computation of second level model done in 0.08111000061035156 seconds

[NiftiMasker.wrapped] Loading data from Nifti1Image(
shape=(168, 255, 129, 65),
affine=array([[ 0.075     ,  0.        ,  0.        , -6.26999998],
       [ 0.        ,  0.075     ,  0.        , -8.18999958],
       [ 0.        ,  0.        ,  0.075     , -4.19999981],
       [ 0.        ,  0.        ,  0.        ,  1.        ]])
)
[NiftiMasker.wrapped] Extracting region signals
[NiftiMasker.wrapped] Cleaning extracted signals
Traceback (most recent call last):
  File "[redacted]/scripts/stats.py", line 162, in <module>
    output = non_parametric_inference(
  File "[redacted]/env/analysis/lib/python3.9/site-packages/nilearn/glm/second_level/second_level.py", line 1147, in non_parametric_inference
    outputs = permuted_ols(
  File "[redacted]/env/analysis/lib/python3.9/site-packages/nilearn/mass_univariate/permuted_least_squares.py", line 736, in permuted_ols
    tfce_original_data = calculate_tfce(
  File "[redacted]/env/analysis/lib/python3.9/site-packages/nilearn/mass_univariate/_utils.py", line 82, in calculate_tfce
    score_threshs = np.arange(step, max_score + step, step)
ValueError: arange: cannot compute length
```

These second level inputs are derived from the same images, have the same masks, and have the same number of permutations, so I am leaning towards the difference being the input as @tsalo suggested.

I haven't had time to dig into the input arrays yet to see what they _really_ look like, but if I can confirm that there's some rogue NaNs somewhere, maybe some sort of check to make sure that the whole input array is valid would be helpful?

**Comment by bthirion** [comment]
Ideally, you would like to reproduce the bug to make sure you identify it. 
Are you sure that it's not something like no voxel is higher than the cluster-forming threshold ? (or potentially too few voxels ?)

**Comment by eilidhmacnicol** [comment]
While tracing the error above, I noticed that the offending line, `score_threshs = np.arange(step, max_score + step, step)`, was actually replaced recently (#5179). I've updated my nilearn with respect to main, and I'm submitting the batch again, but early indications (namely the permutation testing starting) suggest that the TFCE calculation is successful and is no longer a problem.
