### ISSUE TITLE
Memory error when running signal.clean (function using all the RAM on a 128GB RAM system!)

### ISSUE THREAD

**Issue by bwinsto2** [nilearn/nilearn#3598]
Running into MemoryErrors when running `clean.signal` (specifically the `cubic_spline_fitter` for scrubbing). My system is 128GB RAM, so this is surprising that it's so resource intensive:
<img width="601" alt="Screen Shot 2023-03-15 at 11 54 15 PM" src="https://user-images.githubusercontent.com/61159065/225511814-f1ed6d64-fac7-4525-bed1-9b0ddf76dc5a.png">

It would be great if someone could help me out. I copied the errors that I'm getting and also the function I wrote, which loads in confounds and does signal cleaning for fMRI image. 

Nilearn version:
0.10.0

### Actual behavior
First I got this error:
```python
clean_img = nuisance_regression('/data/2104/derivatives/fmriprep/sub-21040005/ses-3/func/sub-21040005_ses-3_task-movie_run-1_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz', '/data/2104/derivatives/fmriprep/sub-21040005/ses-3/func/sub-21040005_ses-3_task-movie_run-1_desc-confounds_timeseries.tsv', 0.8, 4, 0.9)
Identified 11/1592 volumes for scrubbing
Traceback (most recent call last):

  File "<ipython-input-19-2296996f0f65>", line 1, in <module>
	clean_img = nuisance_regression('/data/2104/derivatives/fmriprep/sub-21040005/ses-3/func/sub-21040005_ses-3_task-movie_run-1_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz', '/data/2104/derivatives/fmriprep/sub-21040005/ses-3/func/sub-21040005_ses-3_task-movie_run-1_desc-confounds_timeseries.tsv', 0.8, 4, 0.9)

  File "/usr/local/CPCR-Repository/projects/imaging_fxns/fmri_cleaning", line 88, in nuisance_regression
	t_r = tr, sample_mask = sample_mask).T

  File "/usr/local/anaconda3/lib/python3.7/site-packages/nilearn/signal.py", line 629, in clean
	t_r)

  File "/usr/local/anaconda3/lib/python3.7/site-packages/nilearn/signal.py", line 693, in _handle_scrubbed_volumes
	signals = _interpolate_volumes(signals, sample_mask, t_r)

  File "/usr/local/anaconda3/lib/python3.7/site-packages/nilearn/signal.py", line 714, in _interpolate_volumes
	cubic_spline_fitter = CubicSpline(remained_vol, remained_x)

  File "/usr/local/anaconda3/lib/python3.7/site-packages/scipy/interpolate/_cubic.py", line 629, in __init__
	x, dx, y, axis, _ = prepare_input(x, y, axis)

  File "/usr/local/anaconda3/lib/python3.7/site-packages/scipy/interpolate/_cubic.py", line 41, in prepare_input
	y = y.astype(dtype, copy=False)

MemoryError: Unable to allocate 10.6 GiB for an array with shape (1581, 902629) and data type float64
```
Then I ran it again in a new console and got this:
```python
Traceback (most recent call last):

  File "<ipython-input-2-2296996f0f65>", line 1, in <module>
	clean_img = nuisance_regression('/data/2104/derivatives/fmriprep/sub-21040005/ses-3/func/sub-21040005_ses-3_task-movie_run-1_space-MNI152NLin6Asym_res-2_desc-preproc_bold.nii.gz', '/data/2104/derivatives/fmriprep/sub-21040005/ses-3/func/sub-21040005_ses-3_task-movie_run-1_desc-confounds_timeseries.tsv', 0.8, 4, 0.9)

  File "/usr/local/CPCR-Repository/projects/imaging_fxns/fmri_cleaning", line 89, in nuisance_regression
	t_r = tr, sample_mask = sample_mask).T

  File "/usr/local/anaconda3/lib/python3.7/site-packages/nilearn/signal.py", line 629, in clean
	t_r)

  File "/usr/local/anaconda3/lib/python3.7/site-packages/nilearn/signal.py", line 693, in _handle_scrubbed_volumes
	signals = _interpolate_volumes(signals, sample_mask, t_r)

  File "/usr/local/anaconda3/lib/python3.7/site-packages/nilearn/signal.py", line 714, in _interpolate_volumes
	cubic_spline_fitter = CubicSpline(remained_vol, remained_x)

  File "/usr/local/anaconda3/lib/python3.7/site-packages/scipy/interpolate/_cubic.py", line 784, in __init__
	super().__init__(x, y, s, axis=0, extrapolate=extrapolate)

  File "/usr/local/anaconda3/lib/python3.7/site-packages/scipy/interpolate/_cubic.py", line 146, in __init__
	c = np.empty((4, len(x) - 1) + y.shape[1:], dtype=t.dtype)

MemoryError: Unable to allocate 42.5 GiB for an array with shape (4, 1580, 902629) and data type float64
```
No idea why it's making an array of this shape.

### Steps and code to reproduce bug
Call to this function above in error message:
```python
def nuisance_regression(img, confound_tsv, tr, fwhm, fd_thresh):
	#load fmriprep confounds, calculate motion mask
	confounds, sample_mask = load_confounds(img, strategy = ['motion','compcor','scrub','high_pass'],
                                        	motion = 'full', compcor = 'anat_combined', n_compcor = 10,
                                        	demean = False, fd_threshold = fd_thresh, scrub = 0)
	print(f'Identified {len(confounds) - len(sample_mask)}/{len(confounds)} volumes for scrubbing')

	#nifti image to 4d np array
	raw_img = niftis.get_nii_data(img)
    
	#flatten to 2d and transpose
	vts = niftis.voxel_x_ts(raw_img).T
    
	#nuisance regression (and transpose back)
	clean_img = signal.clean(vts, confounds = confounds,
                         	detrend = False, standardize = False,
                         	t_r = tr, sample_mask = sample_mask).T
    
	#reshape back into 4d, turn into niimg
	clean_img = niftis.vts_to_brain(clean_img, raw_img.shape)
	clean_img = nimg.new_img_like(img, clean_img)
    
	#spatially smooth
	clean_img = nimg.smooth_img(clean_img, fwhm)    
    
	#plot 50th volume for QC purposes
	nplot.plot_epi(clean_img.slicer[:,:,:,50])

	return clean_img

```
any help would be very appreciated <3

```python

```

**Comment by bwinsto2** [comment]
Thanks I was able to resolve the issue by using NiftiMasker
