### ISSUE TITLE
[BUG] second-level contrasts in string format in non_parametric_permutation()

### ISSUE THREAD

**Issue by LineKruse** [nilearn/nilearn#3807]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

Linux Ubuntu 22.04

### Python version

- [ ] 3.11
- [X] 3.10
- [ ] 3.9
- [ ] 3.8
- [ ] 3.7

### nilearn version

0.10.0

### Expected behavior

It is possible to define second_level_contrast as string using column names and +/- signs for computing second level contrast, but not when running non_parametric_permutation(). It seems that the _get_contrast() function that the permutation function is using, does not check the contrast input in a appropriate manner (it checks if it matches a column in design matrix, but it does not as it consists of two columns subtracted from each other - e.g., second_level_contrast='female-male'). 
As this contrast format works for computing contrasts, it should also work in permutation, so that we can run non parametric corrections of the p-values. 

### Current behavior & error messages

This is what I got:

```bash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 17, in permutation_test_and_figure
  File "/users/line/miniconda3/envs/env_bidscoin3/lib/python3.10/site-packages/nilearn/glm/second_level/second_level.py", line 921, in non_parametric_inference
    contrast = _get_contrast(second_level_contrast, design_matrix)
  File "/users/line/miniconda3/envs/env_bidscoin3/lib/python3.10/site-packages/nilearn/glm/second_level/second_level.py", line 239, in _get_contrast
    raise ValueError(
ValueError: "female-male" is not a valid contrast name
```

### Steps and code to reproduce bug

```python
from nilearn.datasets import fetch_localizer_contrasts

n_subjects = 16
data = fetch_localizer_contrasts(
    ["left vs right button press"],
    n_subjects,
    get_tmaps=True,
    legacy_format=False,
)

import pandas as pd
import random 

k = random.randint(0, 1) # decide on k once
male = []
for i in range(0,len(second_level_input)):
    male.append(random.randint(0,1))
female = male 
female[male==1] = 0
female[male==0] = 1

second_level_input = data["cmaps"]
design_matrix = pd.DataFrame(
    [1] * len(second_level_input),
    male, 
    female, 
    columns=["intercept", "male", "female"],
)

from nilearn.glm.second_level import SecondLevelModel

second_level_model = SecondLevelModel(smoothing_fwhm=8.0)
second_level_model = second_level_model.fit(
    second_level_input,
    design_matrix=design_matrix,
)

z_map = second_level_model.compute_contrast(
    second_level_contrast="female-male",
    output_type="z_score",
)

import numpy as np 
from nilearn.image import get_data, math_img 
from nilearn.glm.second_level import non_parametric_inference

p_val = second_level_model.compute_contrast(output_type='p_value', second_level_contrast=sl_contrast)
#Get the number of voxels in the image 
n_voxels = np.sum(get_data(slm.masker_.mask_img_))
#Making an image with significant values, correcting the p-values for multiple testing and taking negative log 
neg_log_pval = math_img(
        '-np.log10(np.minimum(1, img * {}))'.format(str(n_voxels)),
        img=p_val)

n_perm = 1000 
#Calculate p-values using permutations 
out_dict = non_parametric_inference(
        second_level_input,
        design_matrix=design_matrix,
        second_level_contrast="female-male",
        model_intercept=True,
        n_perm=n_perm,  
        two_sided_test=False,
        smoothing_fwhm=8.0,
        n_jobs=1  
        )

```

**Comment by Remi-Gau** [comment]
thanks for the bug report

had to tweak a couple of lines on the code you provided but I can reproduce the issue you described

```python
from nilearn.datasets import fetch_localizer_contrasts

n_subjects = 16
data = fetch_localizer_contrasts(
    ["left vs right button press"],
    n_subjects,
    get_tmaps=True,
    legacy_format=False,
)

import pandas as pd
import random 

second_level_input = data["cmaps"]

k = random.randint(0, 1) # decide on k once
male = []
for i in range(0,len(second_level_input)):
    male.append(random.randint(0,1))
female = male 
female[male==1] = 0
female[male==0] = 1

data = {"intercept": [1] * len(second_level_input), 
         "male": male,
         "female": female}

design_matrix = pd.DataFrame(data)

from nilearn.glm.second_level import SecondLevelModel

second_level_model = SecondLevelModel(smoothing_fwhm=8.0)
second_level_model = second_level_model.fit(
    second_level_input,
    design_matrix=design_matrix,
)

sl_contrast = "female-male"

z_map = second_level_model.compute_contrast(
    second_level_contrast=sl_contrast,
    output_type="z_score",
)

import numpy as np 
from nilearn.image import get_data, math_img 
from nilearn.glm.second_level import non_parametric_inference

p_val = second_level_model.compute_contrast(output_type='p_value', second_level_contrast=sl_contrast)
#Get the number of voxels in the image 
n_voxels = np.sum(get_data(second_level_model.masker_.mask_img_))
#Making an image with significant values, correcting the p-values for multiple testing and taking negative log 
neg_log_pval = math_img(
        '-np.log10(np.minimum(1, img * {}))'.format(str(n_voxels)),
        img=p_val)

n_perm = 1000 
#Calculate p-values using permutations 
out_dict = non_parametric_inference(
        second_level_input,
        design_matrix=design_matrix,
        second_level_contrast="female-male",
        model_intercept=True,
        n_perm=n_perm,  
        two_sided_test=False,
        smoothing_fwhm=8.0,
        n_jobs=1  
        )

```

**Comment by ymzayek** [comment]
@Remi-Gau any update on this? Happy to take over

**Comment by Remi-Gau** [comment]
Can't remember why I stopped digging on this. From the top of my (failing) head, it was either that there was some refactoring ongoing for that code I wanted to get done first (yeah right... 😏) or that it was less trivial than I thought...

If you have the bandwidth go for it

**Comment by ymzayek** [comment]
I guess I'm wondering why a separate function `_get_contrast` was created for use with `non_parameteric_inference` instead of just using `_get_con_val` that handles these expressions for `second_level_model.compute_contrast`. @bthirion
Is it just for compatibility with `permuted_ols`?

For the example given we could just create a gender column and set the parameter `second_level_contrast="gender"` to achieve the same thing no?

**Comment by Remi-Gau** [comment]
Also reported in https://github.com/nilearn/nilearn/issues/4140

**Comment by Remi-Gau** [comment]
Adapted code to reproduce and test

```python
from nilearn.datasets import fetch_localizer_contrasts

n_subjects = 16
data = fetch_localizer_contrasts(
    ["left vs right button press"],
    n_subjects,
    get_tmaps=True,
    legacy_format=False,
)

import pandas as pd
import random 

second_level_input = data["cmaps"]

k = random.randint(0, 1) # decide on k once
male = []
female = []
for i in range(0,len(second_level_input)):
    value = random.randint(0,1)
    male.append(value)
    if value == 0:
        female.append(1)
    else:
        female.append(0)

data = {"intercept": [1] * len(second_level_input), 
         "male": male,
         "female": female}

design_matrix = pd.DataFrame(data)

print(design_matrix)

from nilearn.glm.second_level import SecondLevelModel

second_level_model = SecondLevelModel(smoothing_fwhm=8.0)
second_level_model = second_level_model.fit(
    second_level_input,
    design_matrix=design_matrix,
)

sl_contrast = "female-male"

z_map = second_level_model.compute_contrast(
    second_level_contrast=sl_contrast,
    output_type="z_score",
)

import numpy as np 
from nilearn.image import get_data, math_img 
from nilearn.glm.second_level import non_parametric_inference

p_val = second_level_model.compute_contrast(output_type='p_value', second_level_contrast=sl_contrast)
#Get the number of voxels in the image 
n_voxels = np.sum(get_data(second_level_model.masker_.mask_img_))
#Making an image with significant values, correcting the p-values for multiple testing and taking negative log 
neg_log_pval = math_img(
        '-np.log10(np.minimum(1, img * {}))'.format(str(n_voxels)),
        img=p_val)

n_perm = 1000 
#Calculate p-values using permutations 
out_dict = non_parametric_inference(
        second_level_input,
        design_matrix=design_matrix,
        second_level_contrast="female-male",
        model_intercept=True,
        n_perm=n_perm,  
        two_sided_test=False,
        smoothing_fwhm=8.0,
        n_jobs=1  
        )

print(out_dict)
```
