### ISSUE TITLE
[BUG] Strange behavior in compute_contrast when using it for LSA

### ISSUE THREAD

**Issue by andreifoldes** [nilearn/nilearn#4073]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

- Linux CentOS Linux release 7.6.1810 (Core) 

### Python version

- [ ] 3.11
- [X] 3.10
- [ ] 3.9
- [ ] 3.8
- [ ] 3.7

### nilearn version

0.10.2

### Expected behavior

I wanted to run a modified version of the https://nilearn.github.io/dev/auto_examples/07_advanced/plot_beta_series.html#sphx-glr-auto-examples-07-advanced-plot-beta-series-py tutorial for my data which has multiple runs per participant.

I noticed something I can't quite wrap my head around, notice that I run the firstlevel fit and play around with the run index.
When set to zero, the following runs fine:
```
models[startIdx].fit( models_run_imgs[startIdx][0], models_events_modified_lsa[startIdx][0],  models_confounds_simple[startIdx][0])

models[startIdx].compute_contrast(models[startIdx].design_matrices_[0].columns[0], output_type="effect_size")
```
When set to 1, so does does
```
models[startIdx].fit( models_run_imgs[startIdx][1], models_events_modified_lsa[startIdx][1],  models_confounds_simple[startIdx][1])

models[startIdx].compute_contrast(models[startIdx].design_matrices_[0].columns[0], output_type="effect_size")
```

I assumed that I will be able to fit to multiple runs too!
```
models[startIdx].fit( models_run_imgs[startIdx][0:2], models_events_modified_lsa[startIdx][0:2],  models_confounds_simple[startIdx][0:2])

models[startIdx].compute_contrast(models[startIdx].design_matrices_[0].columns[0], output_type="effect_size")
```

### Current behavior & error messages

When running
```
models[startIdx].fit( models_run_imgs[startIdx][0:2], models_events_modified_lsa[startIdx][0:2],  models_confounds_simple[startIdx][0:2])

models[startIdx].compute_contrast(models[startIdx].design_matrices_[0].columns[0], output_type="effect_size")
```

The fit runs without error, but when trying to compute the contrast of the first event in the design_matrix, which is the same event as was in the other two examples when only one run was fitted.

```
The expression (PresentationAnswer__001) is not valid. This could be due to defining the contrasts using design matrix columns that are invalid python identifiers.
Traceback (most recent call last):
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/scope.py", line 233, in resolve
    return self.resolvers[key]
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/collections/__init__.py", line 986, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/collections/__init__.py", line 978, in __missing__
    raise KeyError(key)
KeyError: 'PresentationAnswer__001'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/scope.py", line 244, in resolve
    return self.temps[key]
KeyError: 'PresentationAnswer__001'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/nilearn/glm/contrasts.py", line 38, in expression_to_contrast_vector
    contrast_vector = df.eval(expression, engine="python").values
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/frame.py", line 4576, in eval
    return _eval(expr, inplace=inplace, **kwargs)
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/eval.py", line 336, in eval
    parsed_expr = Expr(expr, engine=engine, parser=parser, env=env)
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 809, in __init__
    self.terms = self.parse()
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 828, in parse
    return self._visitor.visit(self.expr)
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 421, in visit_Module
    return self.visit(expr, **kwargs)
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 424, in visit_Expr
    return self.visit(node.value, **kwargs)
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 415, in visit
    return visitor(node, **kwargs)
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/expr.py", line 548, in visit_Name
    return self.term_type(node.id, self.env, **kwargs)
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/ops.py", line 86, in __init__
    self._value = self._resolve_name()
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/ops.py", line 110, in _resolve_name
    res = self.env.resolve(local_name, is_local=is_local)
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/pandas/core/computation/scope.py", line 246, in resolve
    raise UndefinedVariableError(key, is_local) from err
pandas.errors.UndefinedVariableError: name 'PresentationAnswer__001' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/nilearn/glm/first_level/first_level.py", line 813, in compute_contrast
    con_vals[cidx] = expression_to_contrast_vector(
  File "/home/saptaf1/anaconda3/envs/spy310/lib/python3.10/site-packages/nilearn/glm/contrasts.py", line 40, in expression_to_contrast_vector
    raise ValueError(
ValueError: The expression (PresentationAnswer__001) is not valid. This could be due to defining the contrasts using design matrix columns that are invalid python identifiers.
```

### Steps and code to reproduce bug

```python
Is there a multirun dataset in the nilearn library I can use to reproduce this with another dataset?

```

**Comment by Remi-Gau** [comment]
I was just starting to work on https://github.com/nilearn/nilearn/issues/2401 and creating some tests for it. Let me try to see if I can reproduce this.

**Comment by Remi-Gau** [comment]
Tried to reproduce with the following code and I cannot reproduce it.

Rereading your error I am getting the feeling that some of your runs do not have all the conditions you are trying to create a contrast for.

```python

from nilearn._utils.data_gen import (
    create_fake_bids_dataset,
)
from nilearn.glm.first_level import (
    first_level_from_bids,
)

def test_first_level_from_bids_slice_runs():
    """One condition is missing in one events.tsv file."""
    bids_dataset = create_fake_bids_dataset(
        n_sub=1,
        n_ses=2,
        tasks=["main"],
        n_runs=[2],
        n_voxels=10,
    )

    models, run_imgs, events, confounds = first_level_from_bids(
        dataset_path=bids_dataset,
        task_label="main",
        space_label="MNI",
        slice_time_ref=None,
    )

    sub_idx = 0
    for run_idx in [0, 1 , slice(0,2)]:
        models[sub_idx].fit(run_imgs[sub_idx][run_idx], events[sub_idx][run_idx], confounds[sub_idx][run_idx])
        con_val = models[sub_idx].design_matrices_[0].columns[0]
        models[sub_idx].compute_contrast(con_val, output_type="effect_size")
```

**Comment by andreifoldes** [comment]
Thanks for looking into this. 

> Rereading your error I am getting the feeling that some of your runs do not have all the conditions you are trying to create a contrast for.

Were that the case, once model.fit() successfully runs and generates a "cross-run" design matrix, it should still return results for any column we choose from it no? It is my understanding that all columns in the `models[startIdx].design_matrices_[0].columns` should return results!

You hypothesis however would explain why I was able to retrieve beta maps for confound contrasts like "drift_1' etc..

**Comment by Remi-Gau** [comment]
> Were that the case, once model.fit() successfully runs and generates a "cross-run" design matrix, it should still return results for any column we choose from it no? It is my understanding that all columns in the `models[startIdx].design_matrices_[0].columns` should return results!

Not quite.

I can adapt the code I provided to reproduce your error:

```
def test_first_level_from_bids_with_one_condition_missing(tmp_path_factory):
    """One condition is missing in one events.tsv file."""
    n_runs = 3
    n_ses = 2
    bids_dataset = create_fake_bids_dataset(
        base_dir=tmp_path_factory.mktemp("one_condition_missing"),
        n_sub=1,
        n_ses=n_ses,
        tasks=["main"],
        n_runs=[n_runs],
    )
    events_files = get_bids_files(main_path=bids_dataset, file_tag="events")

    # remove rows with "c0" from "trial_type" columns in one events.tsv file
    events = pd.read_csv(events_files[0], sep="\t")
    events = events[events["trial_type"] != "c0"]
    events.to_csv(events_files[0], sep="\t", index=False)

    models, models_run_imgs, models_events, _ = first_level_from_bids(
        dataset_path=bids_dataset,
        task_label="main",
        space_label="MNI",
        slice_time_ref=0,
    )

    models[0].fit(models_run_imgs[0], models_events[0])

    con_val = models[0].design_matrices_[1].columns[0]
    assert con_val == "c0"
    models[0].compute_contrast(con_val)
```

Error: 

```python
ValueError: The expression (c0) is not valid. This could be due to defining the contrasts using design matrix columns that are invalid python identifiers.
```

Maybe check that all your runs have this condition: `PresentationAnswer__001`

**Comment by andreifoldes** [comment]
Right! So the thing with the LSA approach is that we purposefully create a separate regressors for each event so by design we will have events that are only present in a given run!

I assumed that nilearn won't mind because the fit completed without error and I thought surely I should be able to extract the betamap associated with the contrast because it is supposedly stored somehere inside of the model object :)

**Comment by Remi-Gau** [comment]
Oh true this is LSA. I may need to cross check a few things then.

**Comment by bthirion** [comment]
Not sure I fully understood, but if you have designs with different conditions, then you cannot compute contrasts the way you propose. You need to fit  GLMs separate and apply contrasts only where it makes sense.  I tend to think that this is a feature not a bug, but I'm open to discussion.

**Comment by andreifoldes** [comment]
Hm, right, so the in case of an LSA design matrix the results won't differ irrespective of whether one would run them separately for each run vs having the compute_contrast() "intelligently" just return the resulting regressors in a runwise manner?

I concede that in retrospect this might justify the current behavior, but I must say that I'm not quite sure why its required/necessary to have all trials_types in all runs for "compute_contrast()" to make sense? I guess this is a broader point than just LSA about if one has n runs and one trial_type was missing from n-1 runs shouldn't the user be able to extract the fitted betas nontheless?

**Comment by bthirion** [comment]
Well, I see your points, but the problem is  that making `compute_contrast` too intelligent (i.e. able to skip contrasts when they cannot be estimated), then it becomes harder to predict what will come from a given analysis. It will make it harder for users to figure out why the contrast image they sought to generate was not generated  in the first place. Note also that when you give several runs and corresponding design matrices to a GLM object, it will return the fixed effects across runs, which is probably not what you want for LSA. So overall, multi-run fit for LSA does not sound like a good idea to me. 
Please correct me if I misunderstood your comment.

**Comment by andreifoldes** [comment]
I understand. What if there was an alternative method to access the regressors that doesn't involve using compute_contrast's strict expectation of each run having each condition at least once? Or have an additional argument that enables compute_contrast to return estimates based on available events irrespective of whether they were present in all runs...

I'm sorry that I'm gradually drifting away in the conversation from the LSA use-case, but I think it ties in with a broader issue of "how to access betas when not all runs contain all conditions" - should I open a separate ticket for this question?

**Comment by bthirion** [comment]
So, indeed, we give access to some parameters (residuals, rsqaure etc), but not all. There is no direct access to the coefficients. 
Those are stored in  `fmri_glm.results_[run]["ar"].theta`but I agree that this is somewhat hidden and clumsy.
So maybe yes, there would eb room for a get_beta() method. What do people think ?

**Comment by andreifoldes** [comment]
Yes, that would indeed solve my issues. If I understand correctly, having a get_beta() and perhaps a get_variance() would enable more advanced users to compute any T and Z-value for any regressor(s) that compute_contrast() would not return.

**Comment by andreifoldes** [comment]
Understood! I wasn't trying find shortcuts; I thought this approach could  harness having a more accurate estimate for comparing "condition_b" which was present in all three runs and "condition_a" which was only in a subset :)

**Comment by bthirion** [comment]
OK. This is a case we had not foreseen !
