### ISSUE TITLE
[BUG] `make_glm_report` fails in `examples/04_glm_first_level/plot_fiac_analysis.py` with `height_control="fdr"`

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4203]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 22.04

### Python version

- [ ] 3.12
- [X] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

dev version

### Expected behavior

`make_glm_report` should run with all height_control or give more meaningful errors

### Current behavior & error messages

This is what I got:

```bash
# Paste the error message here
Traceback (most recent call last):
  File "/home/remi/github/nilearn/nilearn/examples/04_glm_first_level/plot_fiac_analysis.py", line 170, in <module>
    report = make_glm_report(fmri_glm,
             ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/reporting/glm_reporter.py", line 230, in make_glm_report
    all_components = _make_stat_maps_contrast_clusters(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/reporting/glm_reporter.py", line 778, in _make_stat_maps_contrast_clusters
    stat_map_svg = _stat_map_to_svg(
                   ^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/reporting/glm_reporter.py", line 941, in _stat_map_to_svg
    stat_map_plot = plot_stat_map(
                    ^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/plotting/img_plotting.py", line 1289, in plot_stat_map
    display = _plot_img_with_bg(
              ^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/plotting/img_plotting.py", line 268, in _plot_img_with_bg
    display.add_overlay(
  File "/home/remi/github/nilearn/nilearn/nilearn/plotting/displays/_slicers.py", line 316, in add_overlay
    self._show_colorbar(
  File "/home/remi/github/nilearn/nilearn/nilearn/plotting/displays/_slicers.py", line 538, in _show_colorbar
    ticks = _get_cbar_ticks(cbar_vmin, cbar_vmax, offset, nb_ticks)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/plotting/displays/_slicers.py", line 823, in _get_cbar_ticks
    if offset is not None and offset / vmax > 0.12:
                              ~~~~~~~^~~~~~
ZeroDivisionError: float division by zero

```

### Steps and code to reproduce bug

```python
# run the example but use this at line 170
report = make_glm_report(fmri_glm,
                         contrasts,
                         bg_img=mean_img_,
                         height_control="fdr",
                         )
```

This was adapted from `nilearn/reporting/_visual_testing/_glm_reporter_visual_inspection_suite_.py`

**Comment by bthirion** [comment]
Indeed...

**Comment by Remi-Gau** [comment]
minimal code to reproduce

seems specific to a single contrast

```
from nilearn.datasets import func
import numpy as np
import pandas as pd
from nilearn.glm.first_level import FirstLevelModel
from nilearn.reporting import make_glm_report


def _pad_vector(contrast_, n_columns):
    """Append zeros in contrast vectors."""
    return np.hstack((contrast_, np.zeros(n_columns - len(contrast_))))


data = func.fetch_fiac_first_level()
fmri_imgs = [data["func1"], data["func2"]]

design_files = [data["design_matrix1"], data["design_matrix2"]]
design_matrices = [pd.DataFrame(np.load(df)["X"]) for df in design_files]

fmri_glm = FirstLevelModel(mask_img=data["mask"])

fmri_glm.fit(fmri_imgs, design_matrices=design_matrices)

n_columns = design_matrices[0].shape[1]
contrasts = {
    "DSt_minus_SSt": _pad_vector([-1, -1, 1, 1], n_columns),
}

report = make_glm_report(
    fmri_glm,
    contrasts,
    height_control="bonferroni",
)
```

**Comment by Remi-Gau** [comment]
Bug did not occur with version 0.10.2

**Comment by Remi-Gau** [comment]
will run git bisect on this

**Comment by Remi-Gau** [comment]
d53ba5830207546744fdda3071f55620ea946b8d is the first bad commit

**Comment by Remi-Gau** [comment]
This was due to a plotting issue: finding the right ticks would fail for vmax=0: either when passed as argument or because the maximum value in the image is actually 0.
