### ISSUE TITLE
[BUG] unhepful error message when passing invalid `view` to surface plotting

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4294]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 22.04

### Python version

- [ ] 3.12
- [X] 3.11
- [ ] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

dev

### Expected behavior

when passing is view of a type that is does not match what's in the doc string that is not a string (e.g `"lateral"`, `"medial"`...) or a pair of floats (elevation, azimuth) I would expect an informative error.

### Current behavior & error messages

This is what I got:

```bash
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/remi/miniconda3/lib/python3.11/tkinter/__init__.py", line 1948, in __call__
    return self.func(*args)
           ^^^^^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.11/tkinter/__init__.py", line 861, in callit
    func(*args)
  File "/home/remi/miniconda3/lib/python3.11/site-packages/matplotlib/backends/_backend_tk.py", line 274, in idle_draw
    self.draw()
  File "/home/remi/miniconda3/lib/python3.11/site-packages/matplotlib/backends/backend_tkagg.py", line 10, in draw
    super().draw()
  File "/home/remi/miniconda3/lib/python3.11/site-packages/matplotlib/backends/backend_agg.py", line 388, in draw
    self.figure.draw(self.renderer)
  File "/home/remi/miniconda3/lib/python3.11/site-packages/matplotlib/artist.py", line 95, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.11/site-packages/matplotlib/figure.py", line 3154, in draw
    mimage._draw_list_compositing_images(
  File "/home/remi/miniconda3/lib/python3.11/site-packages/matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File "/home/remi/miniconda3/lib/python3.11/site-packages/matplotlib/artist.py", line 72, in draw_wrapper
    return draw(artist, renderer)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.11/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 458, in draw
    self.M = self.get_proj()
             ^^^^^^^^^^^^^^^
  File "/home/remi/miniconda3/lib/python3.11/site-packages/mpl_toolkits/mplot3d/axes3d.py", line 916, in get_proj
    elev_rad = np.deg2rad(self.elev)
               ^^^^^^^^^^^^^^^^^^^^^
TypeError: ufunc 'deg2rad' not supported for the input types, and the inputs could not be safely coerced to any supported types according to the casting rule ''safe''
```

### Steps and code to reproduce bug

```python
from nilearn import datasets
from nilearn import plotting

destrieux_atlas = datasets.fetch_atlas_surf_destrieux()

parcellation = destrieux_atlas["map_left"]

fsaverage = datasets.fetch_surf_fsaverage()

plotting.plot_surf_roi(
    fsaverage["pial_left"],
    roi_map=parcellation,
    hemi="left",
    view=["lateral", "medial"],
    bg_map=fsaverage["sulc_left"],
    bg_on_data=True,
    darkness=0.5,
)
plotting.show()
```

**Comment by bthirion** [comment]
Indeed, the message does not make sense.
