### ISSUE TITLE
passing nifti to surface plotting functions fails

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4312]
> Also, in this case you pass the statistical map as a texture, not as a 3D volume per se, so I'm not sure how it would affect.

I was trying to stay close to the code you provided but this did lead me to try passing the path to a nifti image as stat map as `stat_map` as the doc string says it should be ok but this does not seem to work:

![image](https://github.com/nilearn/nilearn/assets/6961185/2482e5f9-0f5c-407d-8f86-f169a3c17334)

```python
import matplotlib.pyplot as plt
import numpy as np

from nilearn import datasets, plotting, surface

fsaverage = datasets.fetch_surf_fsaverage()
curv_left = surface.load_surf_data(fsaverage.curv_left)
curv_left_sign = np.sign(curv_left)

stat_map = datasets.load_sample_motor_activation_image()

print(stat_map)

# %%
engine = "matplotlib"

plotting.plot_surf_stat_map(
    fsaverage.infl_left,
    stat_map = stat_map,
    hemi="left",
    title="Surface left hemisphere",
    cmap = 'bwr',
    colorbar=True,
    threshold=1.0,
    bg_map=curv_left_sign,
    engine=engine,
    symmetric_cbar=False,
    avg_method="mean",
)
```

gives

```
/home/remi/github/nilearn/nilearn/nilearn/datasets/data/image_10426.nii.gz

Traceback (most recent call last):
  File "/home/remi/github/nilearn/nilearn/tmp.py", line 22, in <module>
    plotting.plot_surf_stat_map(
  File "/home/remi/github/nilearn/nilearn/nilearn/plotting/surf_plotting.py", line 1167, in plot_surf_stat_map
    display = plot_surf(
              ^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/plotting/surf_plotting.py", line 809, in plot_surf
    fig = _plot_surf_matplotlib(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/plotting/surf_plotting.py", line 580, in _plot_surf_matplotlib
    surf_map_faces = _compute_surf_map_faces_matplotlib(
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/plotting/surf_plotting.py", line 366, in _compute_surf_map_faces_matplotlib
    surf_map_data = _check_surf_map(surf_map, n_vertices)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/plotting/surf_plotting.py", line 345, in _check_surf_map
    raise ValueError("'surf_map' can only have one dimension "
ValueError: 'surf_map' can only have one dimension but has '3' dimensions
```

_Originally posted by @Remi-Gau in https://github.com/nilearn/nilearn/issues/4296#issuecomment-1983479419_

**Comment by Remi-Gau** [comment]
@bthirion 
Has it ever been possible to pass directly a nifti to any of the surface plotting functions without using `vol_to_surf` first to project it on a surface?

I cannot see any test that suggest this is the case but I may be missing something.

If not then this "bug" seems like an inconsistency between what the doc says and what the code does and could be resolved but just saying that stat_map cannot be a string pointing to a nifti image.

**Comment by bthirion** [comment]
IIRC we have not supported this. Maybe @jeromedockes can correct me on this.
I'd be in favor of udpating the docstring (+potentially revising the doc to be more explicit).

**Comment by Remi-Gau** [comment]
OK I will try to clarify the doc.

Would it make sense to also check the extension of the files passed is among the supported ones? To align the doc with the code behavior? 

Because even if we change the doc string the users would still get the error reported above which is not super useful to figure out that nifti are not supported.

**Comment by Remi-Gau** [comment]
nope

A check of the extensions is already performed here:

https://github.com/nilearn/nilearn/blob/284a6ff1fe76898e3806f964a03780bb5f0283f9/nilearn/surface/surface.py#L757-L767

With those extensions as supported:

https://github.com/nilearn/nilearn/blob/284a6ff1fe76898e3806f964a03780bb5f0283f9/nilearn/surface/surface.py#L693-L710

I would suggest extracting this check into a separate private function that we can call earlier with for the plotting functions that do not support niftis:

```python
def _check_extensions(surf_data, data_extensions, freesurfer_data_extensions):
    if (not any(surf_data.endswith(x)
            for x in data_extensions +
            freesurfer_data_extensions)):
        raise ValueError(
            'The input type is not recognized. '
            f'{surf_data!r} was given '
            'while valid inputs are a Numpy array '
            'or one of the following file formats: '
            f"{_stringify(data_extensions)}, "
            'Freesurfer specific files such as '
            f"{_stringify(freesurfer_data_extensions)}.")
```

It is not ideal because this check would be performed twice in the end for most cases, but I don't think is a costly check.

**Comment by bthirion** [comment]
Maybe in another PR so that we can think more globally where such an extension check is needed.
