### ISSUE TITLE
[BUG] Matplotlib colormap not recognized in `reporter_visual_inspection_suite.py` due to British/Canadian spelling

### ISSUE THREAD

**Issue by michellewang** [nilearn/nilearn#4351]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [ ] Linux
- [X] Mac
- [ ] Windows

### Operating system version

macOS Ventura 13.2.1

### Python version

- [ ] 3.12
- [ ] 3.11
- [ ] 3.10
- [X] 3.9
- [ ] 3.8

### nilearn version

Nilearn `0.10.4.dev3+g29ae5f12f`
Matplotlib `3.6.3`

### Expected behavior

The `doc/visual_testing/reporter_visual_inspection_suite.py` script runs without crashing when I try to build the docs.

### Current behavior & error messages

Matplotlib complains that the `"grey"` colormap doesn't exist. Replacing all instances of `"grey"` with `"gray"` seems to fix the issue. It looks like Matplotlib only added aliases for British vs American spelling for the colormaps in version `3.8.0` (see [here](https://github.com/matplotlib/matplotlib/pull/26003)), but [the Nilearn minimum version is `3.3.0`](https://github.com/nilearn/nilearn/blob/main/pyproject.toml#L73).

```bash
Generating masker reports templates

Traceback (most recent call last):
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/doc/visual_testing/reporter_visual_inspection_suite.py", line 436, in <module>
    report_nifti_masker()
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/doc/visual_testing/reporter_visual_inspection_suite.py", line 344, in report_nifti_masker
    report = masker.generate_report()
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/nilearn/maskers/nifti_masker.py", line 308, in generate_report
    return generate_report(self)
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/nilearn/reporting/html_report.py", line 236, in generate_report
    return _create_report(estimator, data)
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/nilearn/reporting/html_report.py", line 241, in _create_report
    overlay, image = _define_overlay(estimator)
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/nilearn/reporting/html_report.py", line 164, in _define_overlay
    displays = estimator._reporting()
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/nilearn/maskers/nifti_masker.py", line 362, in _reporting
    init_display = plotting.plot_img(
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/nilearn/plotting/img_plotting.py", line 422, in plot_img
    display = _plot_img_with_bg(
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/nilearn/plotting/img_plotting.py", line 274, in _plot_img_with_bg
    display.add_overlay(
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/nilearn/plotting/displays/_slicers.py", line 308, in add_overlay
    ims = self._map_show(img, type="imshow", threshold=threshold, **kwargs)
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/nilearn/plotting/displays/_slicers.py", line 469, in _map_show
    im = display_ax.draw_2d(
  File "/Users/michellewang/Documents/Projects/nilearn/nilearn_repo/nilearn/plotting/displays/_axes.py", line 74, in draw_2d
    im = getattr(ax, type)(
  File "/Users/michellewang/opt/anaconda3/envs/nilearn/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/Users/michellewang/opt/anaconda3/envs/nilearn/lib/python3.9/site-packages/matplotlib/__init__.py", line 1433, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "/Users/michellewang/opt/anaconda3/envs/nilearn/lib/python3.9/site-packages/matplotlib/axes/_axes.py", line 5603, in imshow
    im = mimage.AxesImage(self, cmap=cmap, norm=norm,
  File "/Users/michellewang/opt/anaconda3/envs/nilearn/lib/python3.9/site-packages/matplotlib/_api/deprecation.py", line 454, in wrapper
    return func(*args, **kwargs)
  File "/Users/michellewang/opt/anaconda3/envs/nilearn/lib/python3.9/site-packages/matplotlib/image.py", line 922, in __init__
    super().__init__(
  File "/Users/michellewang/opt/anaconda3/envs/nilearn/lib/python3.9/site-packages/matplotlib/image.py", line 260, in __init__
    cm.ScalarMappable.__init__(self, norm, cmap)
  File "/Users/michellewang/opt/anaconda3/envs/nilearn/lib/python3.9/site-packages/matplotlib/cm.py", line 415, in __init__
    self.set_cmap(cmap)  # The Colormap instance of this ScalarMappable.
  File "/Users/michellewang/opt/anaconda3/envs/nilearn/lib/python3.9/site-packages/matplotlib/cm.py", line 603, in set_cmap
    self.cmap = _ensure_cmap(cmap)
  File "/Users/michellewang/opt/anaconda3/envs/nilearn/lib/python3.9/site-packages/matplotlib/cm.py", line 741, in _ensure_cmap
    _api.check_in_list(sorted(_colormaps), cmap=cmap_name)
  File "/Users/michellewang/opt/anaconda3/envs/nilearn/lib/python3.9/site-packages/matplotlib/_api/__init__.py", line 131, in check_in_list
    raise ValueError(msg)
ValueError: 'grey' is not a valid value for cmap; supported values are 'Accent', 'Accent_r', 'Blues', 'Blues_r', 'BrBG', 'BrBG_r', 'BuGn', 'BuGn_r', 'BuPu', 'BuPu_r', 'CMRmap', 'CMRmap_r', 'Dark2', 'Dark2_r', 'GnBu', 'GnBu_r', 'Greens', 'Greens_r', 'Greys', 'Greys_r', 'OrRd', 'OrRd_r', 'Oranges', 'Oranges_r', 'PRGn', 'PRGn_r', 'Paired', 'Paired_r', 'Pastel1', 'Pastel1_r', 'Pastel2', 'Pastel2_r', 'PiYG', 'PiYG_r', 'PuBu', 'PuBuGn', 'PuBuGn_r', 'PuBu_r', 'PuOr', 'PuOr_r', 'PuRd', 'PuRd_r', 'Purples', 'Purples_r', 'RdBu', 'RdBu_r', 'RdGy', 'RdGy_r', 'RdPu', 'RdPu_r', 'RdYlBu', 'RdYlBu_r', 'RdYlGn', 'RdYlGn_r', 'Reds', 'Reds_r', 'Set1', 'Set1_r', 'Set2', 'Set2_r', 'Set3', 'Set3_r', 'Spectral', 'Spectral_r', 'Wistia', 'Wistia_r', 'YlGn', 'YlGnBu', 'YlGnBu_r', 'YlGn_r', 'YlOrBr', 'YlOrBr_r', 'YlOrRd', 'YlOrRd_r', 'afmhot', 'afmhot_r', 'autumn', 'autumn_r', 'binary', 'binary_r', 'black_blue', 'black_blue_r', 'black_green', 'black_green_r', 'black_pink', 'black_pink_r', 'black_purple', 'black_purple_r', 'black_red', 'black_red_r', 'blue_orange', 'blue_orange_r', 'blue_red', 'blue_red_r', 'blue_transparent', 'blue_transparent_full_alpha_range', 'bone', 'bone_r', 'brg', 'brg_r', 'brown_blue', 'brown_blue_r', 'brown_cyan', 'brown_cyan_r', 'bwr', 'bwr_r', 'cividis', 'cividis_r', 'cold_hot', 'cold_hot_r', 'cold_white_hot', 'cold_white_hot_r', 'cool', 'cool_r', 'coolwarm', 'coolwarm_r', 'copper', 'copper_r', 'cubehelix', 'cubehelix_r', 'cyan_copper', 'cyan_copper_r', 'cyan_orange', 'cyan_orange_r', 'flag', 'flag_r', 'gist_earth', 'gist_earth_r', 'gist_gray', 'gist_gray_r', 'gist_heat', 'gist_heat_r', 'gist_ncar', 'gist_ncar_r', 'gist_rainbow', 'gist_rainbow_r', 'gist_stern', 'gist_stern_r', 'gist_yarg', 'gist_yarg_r', 'gnuplot', 'gnuplot2', 'gnuplot2_r', 'gnuplot_r', 'gray', 'gray_r', 'green_transparent', 'green_transparent_full_alpha_range', 'hot', 'hot_black_bone', 'hot_black_bone_r', 'hot_r', 'hot_white_bone', 'hot_white_bone_r', 'hsv', 'hsv_r', 'inferno', 'inferno_r', 'jet', 'jet_r', 'magma', 'magma_r', 'nipy_spectral', 'nipy_spectral_r', 'ocean', 'ocean_hot', 'ocean_hot_r', 'ocean_r', 'pink', 'pink_r', 'plasma', 'plasma_r', 'prism', 'prism_r', 'purple_blue', 'purple_blue_r', 'purple_green', 'purple_green_r', 'rainbow', 'rainbow_r', 'red_transparent', 'red_transparent_full_alpha_range', 'roy_big_bl', 'seismic', 'seismic_r', 'spring', 'spring_r', 'summer', 'summer_r', 'tab10', 'tab10_r', 'tab20', 'tab20_r', 'tab20b', 'tab20b_r', 'tab20c', 'tab20c_r', 'terrain', 'terrain_r', 'turbo', 'turbo_r', 'twilight', 'twilight_r', 'twilight_shifted', 'twilight_shifted_r', 'videen_style', 'viridis', 'viridis_r', 'winter', 'winter_r'
```

### Steps and code to reproduce bug

Go to `doc/visual_testing`

Run:
```bash
python reporter_visual_inspection_suite.py
```

**Comment by michellewang** [comment]
I can make a PR to change the spelling to `"gray"` if we confirm that it's a Matplotlib version issue and not something being weird on my side

**Comment by Remi-Gau** [comment]
I thought I had fixed this but yes I confirm this only tends to show up on python 3.8 because of the matplotlib version that gets installed.

Open PR at will!

**Comment by Remi-Gau** [comment]
FYI this not mission critical since the bug is in a maintenance script not the code base so this fix does not need to go in the next release.
