### ISSUE TITLE
[BUG] Bug in "Example of surface-based first-level analysis"

### ISSUE THREAD

**Issue by paul-reiners** [nilearn/nilearn#4428]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

NAME="Rocky Linux"
VERSION="8.9 (Green Obsidian)"
ID="rocky"
ID_LIKE="rhel centos fedora"
VERSION_ID="8.9"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Rocky Linux 8.9 (Green Obsidian)"
ANSI_COLOR="0;32"
LOGO="fedora-logo-icon"
CPE_NAME="cpe:/o:rocky:rocky:8:GA"
HOME_URL="https://rockylinux.org/"
BUG_REPORT_URL="https://bugs.rockylinux.org/"
SUPPORT_END="2029-05-31"
ROCKY_SUPPORT_PRODUCT="Rocky-Linux-8"
ROCKY_SUPPORT_PRODUCT_VERSION="8.9"
REDHAT_SUPPORT_PRODUCT="Rocky Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.9"

### Python version

- [ ] 3.12
- [ ] 3.11
- [X] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

0.10.4

### Expected behavior

A plot will appear.

### Current behavior & error messages

This is what I got:

```bash
  Contrast 1 out of 3: left - right button press, right hemisphere
Traceback (most recent call last):
  File "/home/miran045/reine097/projects/niLearnExampleProject/src/nilearn_example_surface-based_first-level_analysis.py", line 131, in <module>
    plotting.plot_surf_stat_map(
  File "/home/miran045/reine097/projects/niLearnExampleProject/venv2/lib/python3.11/site-packages/nilearn/plotting/surf_plotting.py", line 1221, in plot_surf_stat_map
    display = plot_surf(
              ^^^^^^^^^^
  File "/home/miran045/reine097/projects/niLearnExampleProject/venv2/lib/python3.11/site-packages/nilearn/plotting/surf_plotting.py", line 848, in plot_surf
    fig = _plot_surf_matplotlib(
          ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miran045/reine097/projects/niLearnExampleProject/venv2/lib/python3.11/site-packages/nilearn/plotting/surf_plotting.py", line 566, in _plot_surf_matplotlib
    figure = plt.figure(figsize=figsize)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/miran045/reine097/projects/niLearnExampleProject/venv2/lib64/python3.11/site-packages/matplotlib/pyplot.py", line 1022, in figure
    manager = new_figure_manager(
              ^^^^^^^^^^^^^^^^^^^
  File "/home/miran045/reine097/projects/niLearnExampleProject/venv2/lib64/python3.11/site-packages/matplotlib/pyplot.py", line 544, in new_figure_manager
    _warn_if_gui_out_of_main_thread()
  File "/home/miran045/reine097/projects/niLearnExampleProject/venv2/lib64/python3.11/site-packages/matplotlib/pyplot.py", line 521, in _warn_if_gui_out_of_main_thread
    canvas_class = cast(type[FigureCanvasBase], _get_backend_mod().FigureCanvas)
                                                ^^^^^^^^^^^^^^^^^^
  File "/home/miran045/reine097/projects/niLearnExampleProject/venv2/lib64/python3.11/site-packages/matplotlib/pyplot.py", line 353, in _get_backend_mod
    switch_backend(rcParams._get("backend"))
  File "/home/miran045/reine097/projects/niLearnExampleProject/venv2/lib64/python3.11/site-packages/matplotlib/pyplot.py", line 411, in switch_backend
    canvas_class = module.FigureCanvas
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: module 'backend_interagg' has no attribute 'FigureCanvas'. Did you mean: 'FigureCanvasAgg'?

Process finished with exit code 1


```

### Steps and code to reproduce bug

```python
#Prepare data and analysis parameters
#Prepare the timing parameters.
t_r = 2.4
slice_time_ref = 0.5

#Prepare the data. First, the volume-based fMRI data.
from nilearn.datasets import fetch_localizer_first_level

data = fetch_localizer_first_level()
fmri_img = data.epi_img

#Second, the experimental paradigm.
import pandas as pd

events_file = data.events
events = pd.read_table(events_file)

#Project the fMRI image to the surface
#For this we need to get a mesh representing the geometry of the surface.
# We could use an individual mesh, but we first resort to a standard mesh,
# the so-called fsaverage5 template from the FreeSurfer software.
import nilearn

fsaverage = nilearn.datasets.fetch_surf_fsaverage()

#The projection function simply takes the fMRI data and the mesh. Note that those correspond spatially, are they are both in MNI space.
from nilearn import surface

texture = surface.vol_to_surf(fmri_img, fsaverage.pial_right)

#Perform first level analysis
#This involves computing the design matrix and fitting the model. We start by specifying the timing of fMRI frames.
import numpy as np

n_scans = texture.shape[1]
frame_times = t_r * (np.arange(n_scans) + .5)

#Create the design matrix.
#We specify an HRF model containing the Glover model and its time derivative The drift model is implicitly a cosine basis with a period cutoff at 128s.

from nilearn.glm.first_level import make_first_level_design_matrix

design_matrix = make_first_level_design_matrix(frame_times,
                                               events=events,
                                               hrf_model='glover + derivative'
                                               )

#Setup and fit GLM.
#Note that the output consists in 2 variables: labels and fit.
# labels tags voxels according to noise autocorrelation. estimates contains the parameter estimates.
# We keep them for later contrast computation.

from nilearn.glm.first_level import run_glm

labels, estimates = run_glm(texture.T, design_matrix.values)

#Estimate contrasts
#Specify the contrasts.

#For practical purpose, we first generate an identity matrix whose size is the number of columns of the design matrix.

contrast_matrix = np.eye(design_matrix.shape[1])

#At first, we create basic contrasts.

basic_contrasts = {column: contrast_matrix[i]
                   for i, column in enumerate(design_matrix.columns)}

#Next, we add some intermediate contrasts and one contrast adding all conditions with some auditory parts.

basic_contrasts['audio'] = (
    basic_contrasts['audio_left_hand_button_press']
    + basic_contrasts['audio_right_hand_button_press']
    + basic_contrasts['audio_computation']
    + basic_contrasts['sentence_listening'])

# one contrast adding all conditions involving instructions reading
basic_contrasts['visual'] = (
    basic_contrasts['visual_left_hand_button_press']
    + basic_contrasts['visual_right_hand_button_press']
    + basic_contrasts['visual_computation']
    + basic_contrasts['sentence_reading'])

# one contrast adding all conditions involving computation
basic_contrasts['computation'] = (basic_contrasts['visual_computation']
                                  + basic_contrasts['audio_computation'])

# one contrast adding all conditions involving sentences
basic_contrasts['sentences'] = (basic_contrasts['sentence_listening']
                                + basic_contrasts['sentence_reading'])

#Finally, we create a dictionary of more relevant contrasts

#left - right button press: probes motor activity in left versus right button presses.

#audio - visual: probes the difference of activity between listening to some content or reading the same type of content (instructions, stories).

#computation - sentences: looks at the activity when performing a mental computation task versus simply reading sentences.

#Of course, we could define other contrasts, but we keep only 3 for simplicity.

contrasts = {
    'left - right button press': (
        basic_contrasts['audio_left_hand_button_press']
        - basic_contrasts['audio_right_hand_button_press']
        + basic_contrasts['visual_left_hand_button_press']
        - basic_contrasts['visual_right_hand_button_press']
    ),
    'audio - visual': basic_contrasts['audio'] - basic_contrasts['visual'],
    'computation - sentences': (
        basic_contrasts['computation']
        - basic_contrasts['sentences']
    )
}
#Let's estimate the contrasts by iterating over them.

from nilearn import plotting
from nilearn.glm.contrasts import compute_contrast

for index, (contrast_id, contrast_val) in enumerate(contrasts.items()):
    print(f"  Contrast {index + 1:1} out of {len(contrasts)}: "
          f"{contrast_id}, right hemisphere")
    # compute contrast-related statistics
    contrast = compute_contrast(labels, estimates, contrast_val,
                                stat_type='t')
    # we present the Z-transform of the t map
    z_score = contrast.z_score()
    # we plot it on the surface, on the inflated fsaverage mesh,
    # together with a suitable background to give an impression
    # of the cortex folding.
    plotting.plot_surf_stat_map(
        fsaverage.infl_right, z_score, hemi='right',
        title=contrast_id, colorbar=True,
        threshold=3., bg_map=fsaverage.sulc_right)

```

**Comment by Remi-Gau** [comment]
Quick check: are you using pycharm as an IDE?

I am seeing a lot of hits for this error related to pycharm usage.

See for example
https://github.com/matplotlib/matplotlib/issues/23911

**Comment by paul-reiners** [comment]
Yes, I am using PyCharm.

**Comment by Remi-Gau** [comment]
From what I have read it seems that updating pycharm may help with this.

**Comment by Remi-Gau** [comment]
will close this but reopen if you confirm this is coming from us
