### ISSUE TITLE
[BUG] When using NiftiLabelsMasker with an empty confounds DataFrame, the masker raises an error

### ISSUE THREAD

**Issue by mibur1** [nilearn/nilearn#4570]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating system

- [X] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

- Linux Pop!_OS 22.04 LTS

### Python version

- [ ] 3.12
- [ ] 3.11
- [X] 3.10
- [ ] 3.9
- [ ] 3.8

### nilearn version

nilearn 0.10.4

### Expected behavior

I have a GUI that dynamically collects cleaning arguments. If I have no cleaning strategy
```
cleaning_args = {'strategy': []}
confounds, _ = nilearn.interfaces.fmriprep.load_confounds(img, **cleaning_args)
```
I will get an empty confounds data frame. If I then apply e.g. detrending:
```
masker = NiftiLabelsMasker(labels_img=atlas, detrend=True)
time_series = masker.fit_transform(img, confounds=confounds)
```
I would still expect this to work as the detrending should not depend on the confounds (?). However the program crashes with `sklearn.utils._param_validation.InvalidParameterError: The 'n' parameter of gen_even_slices must be an int in the range [1, inf). Got 0 instead.` (see stack trace below).

My current workaround is
```
if confounds.empty:
    confounds = None
```
however I am unsure if this could introduce additional issues in certain edge cases. It might be more appropriate to handle this internally. Please let me know if a PR would be welcome.

### Current behavior & error messages

This is what I got:

```bash
Traceback (most recent call last):
  File "/home/mibur/dfc-multiverse/testing_stuff/test_labelsmasker.py", line 11, in <module>
    time_series = masker.fit_transform(img, confounds=confounds)
  File "/home/mibur/.local/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 273, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.10/site-packages/nilearn/maskers/nifti_labels_masker.py", line 620, in fit_transform
    return self.fit(imgs).transform(
  File "/home/mibur/.local/lib/python3.10/site-packages/sklearn/utils/_set_output.py", line 273, in wrapped
    data_to_wrap = f(self, X, *args, **kwargs)
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.10/site-packages/nilearn/maskers/base_masker.py", line 268, in transform
    return self.transform_single_imgs(
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.10/site-packages/nilearn/maskers/nifti_labels_masker.py", line 724, in transform_single_imgs
    region_signals, (ids, masked_atlas) = self._cache(
  File "/home/mibur/.local/lib/python3.10/site-packages/joblib/memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.10/site-packages/nilearn/maskers/base_masker.py", line 139, in _filter_and_extract
    region_signals = cache(
  File "/home/mibur/.local/lib/python3.10/site-packages/joblib/memory.py", line 353, in __call__
    return self.func(*args, **kwargs)
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.10/site-packages/nilearn/signal.py", line 756, in clean
    confounds = standardize_signal(
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.10/site-packages/nilearn/signal.py", line 70, in standardize_signal
    signals = _detrend(signals, inplace=False) if detrend else signals.copy()
  File "/home/mibur/anaconda3/envs/dfc-multiverse/lib/python3.10/site-packages/nilearn/signal.py", line 284, in _detrend
    for batch in gen_even_slices(signals.shape[1], n_batches):
  File "/home/mibur/.local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 203, in wrapper
    validate_parameter_constraints(
  File "/home/mibur/.local/lib/python3.10/site-packages/sklearn/utils/_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'n' parameter of gen_even_slices must be an int in the range [1, inf). Got 0 instead.
```

### Steps and code to reproduce bug

```python
from nilearn.maskers import NiftiLabelsMasker
from nilearn.interfaces.fmriprep import load_confounds
from nilearn import datasets

atlas = datasets.fetch_atlas_aal()["maps"]
img = "<img.nii.gz>" # has to be an image in an fmriprep outputs folder because of the confounds file
cleaning_args = {'strategy': []}

confounds, _ = load_confounds(img, **cleaning_args)
masker = NiftiLabelsMasker(labels_img=atlas, detrend=True)
time_series = masker.fit_transform(img, confounds=confounds)
```

**Comment by bthirion** [comment]
I'm not sure whether this should be dealt with internally (having  very smart building blocks does not always make pipeline simpler...). @htwangtw I'll  rely on your wisdom here.

**Comment by htwangtw** [comment]
Thank you for bringing this issue to our attention!

I don't like the idea of letting empty confounds to be passed to masker object workflow. In isolation it is a simple problem with a one line solution, but it can introduce several complications. However I have an alternative proposal.

Reasons why I don't want to change it on the masker side:
 
1. This would introduce inconsistent behaviour with what other parameters are parsed currently in masker objects: if the relevant parameters are passed as something that's not `None`, the element would be triggered. 
2. Detrend and confound options are all go under the `signal.clean` function and that function has already been suffering from feature creep where we check what parameters are passed through and what workflow to trigger. It's quite a lot of working memory load for maintainers when reading that code. I have been thinking really hard on how to simplify things recently...
3. Letting masker or signal function handing this internally can be confusing for people who handles your code. The empty data frame is a result of passing nothing to `load_confounds`. It would be better to handle this explicitly in your code, raise warning so users know no confounds were produced.

Following point 3, the alternative way is to add what you proposed to `load_confound` and raise warning when no confound strategies were passed, and output `None` for confounds.
This will make sure `load_confound` outputs are consistent with the input description of signal.clean.

LMK if you think this is a good idea and want to do a PR @mibur1

**Comment by mibur1** [comment]
Thanks for your insights, I think this sounds perfectly reasonable. I will have a closer look into your workflow and create a PR.
