### ISSUE TITLE
[BUG] instantiating a GLM model with a volume mask but fitting on surface images gives confusing error message

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4586]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating system

- [x] Linux
- [ ] Mac
- [ ] Windows

### Operating system version

For example one of the following:
- Linux Ubuntu 22.04

### Python version

- [x] 3.12
- [ ] 3.11
- [ ] 3.10
- [ ] 3.9

### nilearn version

dev

### Expected behavior

fit surface image with model with a volumetric mask should clearly explain what the problem is

### Current behavior & error messages

This is what I got:

```
Traceback (most recent call last):
  File "/home/remi/github/nilearn/nilearn/tmp/2_runs_surf.py", line 60, in <module>
    fmri_glm_run_1 = fmri_glm.fit(run_imgs[0], design_matrices=design_matrices[0])
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/remi/github/nilearn/nilearn/nilearn/glm/first_level/first_level.py", line 787, in fit
    self._prepare_mask(run_imgs[0])
  File "/home/remi/github/nilearn/nilearn/nilearn/glm/first_level/first_level.py", line 1020, in _prepare_mask
    self.masker_.fit(run_img)
  File "/home/remi/github/nilearn/nilearn/nilearn/experimental/surface/maskers.py", line 151, in fit
    self._fit_mask_img(img)
  File "/home/remi/github/nilearn/nilearn/nilearn/experimental/surface/maskers.py", line 116, in _fit_mask_img
    check_same_n_vertices(self.mask_img.mesh, img.mesh)
                          ^^^^^^^^^^^^^^^^^^
AttributeError: 'str' object has no attribute 'mesh'
```

### Steps and code to reproduce bug

```python
import numpy as np
import pandas as pd

from nilearn import surface
from nilearn.datasets import func
from nilearn.experimental.surface import SurfaceImage, load_fsaverage
from nilearn.glm.first_level import FirstLevelModel

data = func.fetch_fiac_first_level()
fmri_imgs = [data["func1"], data["func2"]]

fsaverage5 = load_fsaverage()

run_imgs = []
for volume_image in [data["func1"], data["func2"]]:
    texture_left = surface.vol_to_surf(volume_image, fsaverage5["pial"].parts["left"])
    texture_right = surface.vol_to_surf(volume_image, fsaverage5["pial"].parts["right"])
    run_imgs.append(
        SurfaceImage(
            mesh=fsaverage5["pial"],
            data={
                "left": texture_left.T,
                "right": texture_right.T,
            },
        )
    )

design_files = [data["design_matrix1"], data["design_matrix2"]]
design_matrices = [pd.DataFrame(np.load(df)["X"]) for df in design_files]

fmri_glm = FirstLevelModel(
    mask_img=data["mask"],
    smoothing_fwhm=5,
    minimize_memory=True,
)

contrast_id = "DSt_minus_SSt"
contrast_val = [[-1, -1, 1, 1]]

fmri_glm_run_1 = fmri_glm.fit(run_imgs[0], design_matrices=design_matrices[0])
summary_statistics_run_1 = fmri_glm_run_1.compute_contrast(
    contrast_val,
    output_type="all",
)
```

**Comment by Remi-Gau** [comment]
A similar check should also be done with compute_fixed_effect that can accept a mask.
