### ISSUE TITLE
failures on windows-latest with Python 3.9 and matplotlib==3.3.0

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4720]
We are getting some reliable CI failures on main with the workflow that test our oldest dependencies.

It affects windows with python 3.9 and matplotlib==3.3.0 (all the other dependencies should be the most recent version).

See last week:
https://github.com/nilearn/nilearn/actions/workflows/testing_minimum.yml?query=is%3Afailure+branch%3Amain

As far I can tell the test session contains several warning like:

```
A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.2 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\Scripts\pytest.exe\__main__.py", line 7, in <module>
    sys.exit(console_main())
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 201, in console_main
    code = main()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 156, in main
    config = _prepareconfig(args, plugins)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 341, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 1140, in pytest_cmdline_parse
    self.parse(args)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 1494, in parse
    self._preparse(args, addopts=addopts)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 1398, in _preparse
    self.hook.pytest_load_initial_conftests(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_hooks.py", line 513, in __call__
    return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_manager.py", line 120, in _hookexec
    return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\pluggy\_callers.py", line 103, in _multicall
    res = hook_impl.function(*args)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 1222, in pytest_load_initial_conftests
    self.pluginmanager._set_initial_conftests(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 581, in _set_initial_conftests
    self._try_load_conftest(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 619, in _try_load_conftest
    self._loadconftestmodules(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 659, in _loadconftestmodules
    mod = self._importconftest(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\config\__init__.py", line 710, in _importconftest
    mod = import_path(
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\pathlib.py", line 582, in import_path
    importlib.import_module(module_name)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\_pytest\assertion\rewrite.py", line 184, in exec_module
    exec(co, module.__dict__)
  File "D:\a\nilearn\nilearn\nilearn\conftest.py", line 27, in <module>
    if is_matplotlib_installed():
  File "D:\a\nilearn\nilearn\nilearn\_utils\helpers.py", line 268, in is_matplotlib_installed
    import matplotlib  # noqa: F401
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\matplotlib\__init__.py", line 174, in <module>
    _check_versions()
  File "C:\hostedtoolcache\windows\Python\3.9.13\x64\lib\site-packages\matplotlib\__init__.py", line 159, in _check_versions
    from . import ft2font
AttributeError: _ARRAY_API not found
```

Also leads to 2 tests failures:

```
FAILED nilearn/tests/test_package_import.py::test_import_reporting_should_raise_warning_if_matplotlib_not_installed - ImportError: numpy.core.multiarray failed to import
FAILED nilearn/tests/test_package_import.py::test_import_plotting_should_raise_warning_if_matplotlib_not_installed - ImportError: numpy.core.multiarray failed to import
```

**Comment by Remi-Gau** [comment]
@hndgzkn 
seems the tests you added are allowing to catch an error we had not seen before

- opened https://github.com/nilearn/nilearn/pull/4721 to see if we can 'fix' this by bumping the minimal version of matplotlib

**Comment by Remi-Gau** [comment]
More info: https://numpy.org/devdocs/user/troubleshooting-importerror.html#downstream-importerror-attributeerror-or-c-api-abi-incompatibility
