### ISSUE TITLE
[BUG] doc build failure on main for several examples

### ISSUE THREAD

**Issue by Remi-Gau** [nilearn/nilearn#4910]
All of them point to nilearn/mass_univariate/permuted_least_squares.py

I believe that this must be due to https://github.com/nilearn/nilearn/pull/4875

But the fact that our test suite did not catch this means we have a blind spot somewhere.

##  02_decoding/plot_oasis_vbm.py

https://github.com/nilearn/nilearn/actions/runs/12201002128/job/34077197805#step:13:27267

```
    Traceback (most recent call last):
      File "/home/runner/work/nilearn/nilearn/examples/02_decoding/plot_oasis_vbm.py", line 196, in <module>
        neg_log_pvals, t_scores_original_data, _ = permuted_ols(
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/nilearn/mass_univariate/permuted_least_squares.py", line 781, in permuted_ols
        ret = joblib.Parallel(n_jobs=n_jobs, verbose=verbose)(
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/joblib/parallel.py", line 1098, in __call__
        self.retrieve()
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/joblib/parallel.py", line 975, in retrieve
        self._output.extend(job.get(timeout=self.timeout))
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
        return future.result(timeout=timeout)
      File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/concurrent/futures/_base.py", line 446, in result
        return self.__get_result()
      File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
        raise self._exception
    _pickle.PicklingError: Could not pickle the task to send it to the workers.
```

## 05_glm_second_level/plot_second_level_association_test.py

https://github.com/nilearn/nilearn/actions/runs/12201002128/job/34077197805#step:13:27286

```
    Traceback (most recent call last):
      File "/home/runner/work/nilearn/nilearn/examples/05_glm_second_level/plot_second_level_association_test.py", line 137, in <module>
        neg_log_pvals_permuted_ols_unmasked = non_parametric_inference(
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/nilearn/glm/second_level/second_level.py", line 1119, in non_parametric_inference
        outputs = permuted_ols(
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/nilearn/mass_univariate/permuted_least_squares.py", line 781, in permuted_ols
        ret = joblib.Parallel(n_jobs=n_jobs, verbose=verbose)(
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/joblib/parallel.py", line 1098, in __call__
        self.retrieve()
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/joblib/parallel.py", line 975, in retrieve
        self._output.extend(job.get(timeout=self.timeout))
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
        return future.result(timeout=timeout)
      File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/concurrent/futures/_base.py", line 439, in result
        return self.__get_result()
      File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
        raise self._exception
    _pickle.PicklingError: Could not pickle the task to send it to the workers.
```

## 07_advanced/plot_haxby_mass_univariate.py

https://github.com/nilearn/nilearn/actions/runs/12201002128/job/34077197805#step:13:27307

```
     Traceback (most recent call last):
      File "/home/runner/work/nilearn/nilearn/examples/07_advanced/plot_haxby_mass_univariate.py", line 104, in <module>
        neg_log_pvals, t_scores_original_data, _ = permuted_ols(
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/nilearn/mass_univariate/permuted_least_squares.py", line 781, in permuted_ols
        ret = joblib.Parallel(n_jobs=n_jobs, verbose=verbose)(
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/joblib/parallel.py", line 1098, in __call__
        self.retrieve()
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/joblib/parallel.py", line 975, in retrieve
        self._output.extend(job.get(timeout=self.timeout))
      File "/home/runner/work/nilearn/nilearn/.tox/doc/lib/python3.9/site-packages/joblib/_parallel_backends.py", line 567, in wrap_future_result
        return future.result(timeout=timeout)
      File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/concurrent/futures/_base.py", line 439, in result
        return self.__get_result()
      File "/opt/hostedtoolcache/Python/3.9.20/x64/lib/python3.9/concurrent/futures/_base.py", line 391, in __get_result
        raise self._exception
    _pickle.PicklingError: Could not pickle the task to send it to the workers.
```

**Comment by bthirion** [comment]
Indeed !
