### ISSUE TITLE
intersect_mask raises bug when given a list of filename string

### ISSUE THREAD

**Issue by arthurmensch** [nilearn/nilearn#622]
Calling

```python
from nilearn.masking import intersect_mask
epi_img = intersect_masks(subject_filenames)
```

raises error
```
Traceback (most recent call last):
  File "/home/arthur/repos/internship/tools/intersection.py", line 14, in <module>
    epi_img = intersect_masks(subject_filenames[:10])
  File "/media/data/work/repos/nilearn/nilearn/masking.py", line 162, in intersect_masks
    return new_img_like(mask_imgs[0], grp_mask, ref_affine)
  File "/media/data/work/repos/nilearn/nilearn/_utils/niimg.py", line 96, in new_img_like
    return ref_img.__class__(data, affine, header=header)
TypeError: str() takes at most 1 argument (3 given)
```
 See PR #623 for fix

**Comment by GaelVaroquaux** [comment]
Fixed by #623
