### ISSUE TITLE
weird error related to MKL / numpy / fortran installation ?

### ISSUE THREAD

**Issue by dohmatob** [nilearn/nilearn#781]
Travis throughs a weird error related to MKL / numpy / fortran installation on some DISTRIB="conda" and PYTHON_VERSION="2.7" (reported by @salma1601).

```
Error: no packages found to remove from environment: /home/travis/miniconda/envs/testenv
MKL not installed
Traceback (most recent call last):
  File "setup.py", line 51, in <module>
    module_check_fn(is_nilearn_installing=True)
  File "<string>", line 111, in _check_module_dependencies
  File "<string>", line 61, in _import_module_with_version_check
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/numpy/lib/__init__.py", line 18, in <module>
    from .polynomial import *
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/numpy/lib/polynomial.py", line 19, in <module>
    from numpy.linalg import eigvals, lstsq, inv
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/numpy/linalg/__init__.py", line 50, in <module>
    from .linalg import *
  File "/home/travis/miniconda/envs/testenv/lib/python2.7/site-packages/numpy/linalg/linalg.py", line 29, in <module>
    from numpy.linalg import lapack_lite, _umath_linalg
ImportError: ('libgfortran.so.1: cannot open shared object file: No such file or directory', 'Module "numpy" could not be found. See http://nilearn.github.io/introduction.html#installation for installation information.')
```

**Comment by lesteve** [comment]
numpy 1.8.1 seems to be missing the libgfortran dependency in conda (only for python 2.7 though). I pushed a work-around in master to use numpy 1.8.2 instead. That seems to be working fine.

**Comment by lesteve** [comment]
For completeness, this problem was seen by other projects, see https://github.com/conda/conda/issues/444.
