### ISSUE TITLE
plot_haxby_space_net is broken on Python 3

### ISSUE THREAD

**Issue by arthurmensch** [nilearn/nilearn#998]
`python examples/02_decoding/plot_haxby_space_net.py`

Traceback:
```
/opt/anaconda/lib/python3.5/site-packages/sklearn/externals/joblib/func_inspect.py:191: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  arg_spec = inspect.getargspec(func)
/opt/anaconda/lib/python3.5/site-packages/sklearn/externals/joblib/hashing.py:178: DeprecationWarning: Changing the shape of non-C contiguous array by
descriptor assignment is deprecated. To maintain
the Fortran contiguity of a multidimensional Fortran
array, use 'a.T.view(...).T' instead
  obj_bytes_view = obj.view(self.np.uint8)
/opt/anaconda/lib/python3.5/site-packages/sklearn/externals/joblib/func_inspect.py:191: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  arg_spec = inspect.getargspec(func)
/opt/anaconda/lib/python3.5/site-packages/sklearn/externals/joblib/func_inspect.py:191: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  arg_spec = inspect.getargspec(func)
/opt/anaconda/lib/python3.5/site-packages/sklearn/externals/joblib/hashing.py:178: DeprecationWarning: Changing the shape of non-C contiguous array by
descriptor assignment is deprecated. To maintain
the Fortran contiguity of a multidimensional Fortran
array, use 'a.T.view(...).T' instead
  obj_bytes_view = obj.view(self.np.uint8)
/opt/anaconda/lib/python3.5/site-packages/sklearn/externals/joblib/func_inspect.py:191: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  arg_spec = inspect.getargspec(func)
/opt/anaconda/lib/python3.5/site-packages/sklearn/externals/joblib/hashing.py:178: DeprecationWarning: Changing the shape of non-C contiguous array by
descriptor assignment is deprecated. To maintain
the Fortran contiguity of a multidimensional Fortran
array, use 'a.T.view(...).T' instead
  obj_bytes_view = obj.view(self.np.uint8)
/opt/anaconda/lib/python3.5/site-packages/numpy/core/_methods.py:59: RuntimeWarning: Mean of empty slice.
  warnings.warn("Mean of empty slice.", RuntimeWarning)
/opt/anaconda/lib/python3.5/site-packages/numpy/core/_methods.py:68: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
/opt/anaconda/lib/python3.5/site-packages/sklearn/externals/joblib/func_inspect.py:191: DeprecationWarning: inspect.getargspec() is deprecated, use inspect.signature() instead
  arg_spec = inspect.getargspec(func)
/opt/anaconda/lib/python3.5/site-packages/numpy/core/_methods.py:82: RuntimeWarning: Degrees of freedom <= 0 for slice
  warnings.warn("Degrees of freedom <= 0 for slice", RuntimeWarning)
/opt/anaconda/lib/python3.5/site-packages/numpy/core/_methods.py:94: RuntimeWarning: invalid value encountered in true_divide
  arrmean, rcount, out=arrmean, casting='unsafe', subok=False)
/opt/anaconda/lib/python3.5/site-packages/numpy/core/_methods.py:114: RuntimeWarning: invalid value encountered in true_divide
  ret, rcount, out=ret, casting='unsafe', subok=False)
Traceback (most recent call last):
  File "/home/arthur/work/repos/nilearn/examples/02_decoding/plot_haxby_space_net.py", line 50, in <module>
    decoder.fit(X_train, y_train)
  File "/home/arthur/work/repos/nilearn/nilearn/decoding/space_net.py", line 814, in fit
    classifier=self.is_classif))
  File "/opt/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py", line 1677, in check_cv
    cv = StratifiedKFold(y, cv)
  File "/opt/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py", line 505, in __init__
    len(y), n_folds, shuffle, random_state)
  File "/opt/anaconda/lib/python3.5/site-packages/sklearn/cross_validation.py", line 245, in __init__
    " than the number of samples: {1}.").format(n_folds, n))
ValueError: Cannot have number of folds n_folds=8 greater than the number of samples: 0.
```

**Comment by arthurmensch** [comment]
for some reason `self.masker_.fit_transform(X) == []` in the estimator

**Comment by lesteve** [comment]
Wild guess : a lot of things are iterators rather than lists in Python 3, e.g. zip, map, dict.keys. This could be the case that an iterator is used and looped over once. When you iterate over it again it is empty so you get 0 samples.

**Comment by aabadie** [comment]
maybe @dohmatob is more aware of this code and could help.

**Comment by AlexandreAbraham** [comment]
Easy!

`condition_mask = np.logical_or(target == "face", target == "house")` fails because target is byte encoded. Use b"face", or, better, convert labels to unicode.

**Comment by lesteve** [comment]
Yep I reached the exact same conclusion. Good duplication of effort ;-).

As mentioned in another issue, our downloaders in Python 3 loads all the string data as bytes, which leads to this kind of nasty surprises. AFAICR I could not convince one of the different numpy ways of reading a csv to output strings but maybe I didn't try hard enough.

**Comment by dohmatob** [comment]
Oops! Looks like this is not the first time I'm hearing about this particular py3 problem in this space net example. Fixing OAFA.

**Comment by Naereen** [comment]
Thanks for this check.

The live version of the auto example has not been updated yet, though.

**Comment by GaelVaroquaux** [comment]
I believe that this is fixed. Closing
