### ISSUE TITLE
plot_mixed_gambles_space_net if broken on Python 3

### ISSUE THREAD

**Issue by arthurmensch** [nilearn/nilearn#999]
Simple Python 3 glitch:
```
Traceback (most recent call last):
  File "/home/arthur/work/repos/nilearn/examples/02_decoding/plot_mixed_gambles_space_net.py", line 16, in <module>
    data = fetch_mixed_gambles(n_subjects=16)
  File "/home/arthur/work/repos/nilearn/nilearn/datasets/func.py", line 1285, in fetch_mixed_gambles
    X, y, mask_img = _load_mixed_gambles(map(nibabel.load, data.zmaps))
  File "/home/arthur/work/repos/nilearn/nilearn/datasets/func.py", line 1209, in _load_mixed_gambles
    mask = np.sum(mask, axis=0) > .5 * len(zmap_imgs)
TypeError: object of type 'map' has no len()
```

**Comment by AlexandreAbraham** [comment]
This is surprising. These examples are run routinely in CircleCI without problems.

**Comment by arthurmensch** [comment]
with Python 3 ?

**Comment by AlexandreAbraham** [comment]
OK, CircleCI runs on Python 2. Oooooooold!
